### ISSUE TITLE
Is cron configured for fetching of emails?

### ISSUE THREAD

**Issue by BrianGilbert** [tiredofit/docker-freescout#10]
Can't see anything that looks like it in the dockerfile?

**from /system/status**
Make sure that you have the following line in your crontab:
```
* * * * * php /www/html/artisan schedule:run >> /dev/null 2>&1
```

**Comment by tiredofit** [comment]
Yes, this is a part of the base image. You can find the cron entry in the repo:
./install/assets/cron/crontab.txt

**Comment by aj-saini** [comment]
Hi i am not able to locate the crontab.txt file, can you please share the full path 

my docker-compose.yml

volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    - ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    #- ./data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    #- ./modules:/www/html/Modules
    - ./logs/:/www/logs
    environment:
    
    
  root@test:~# ls
data  db  dbbackup  docker-compose.yml  docker-compose.yml.backup  logs
root@test:~#

**Comment by aj-saini** [comment]
root@test:~/data# find . -name "crontab.txt*"
root@test:~/data#

if someone can help me would be great 

Thank you, I have feeling its something simple, but i am just doing it wrong

Thank you

**Comment by aj-saini** [comment]
@BrianGilbert are you able to access the crontab if yes can you please share the instructions, 
I am fairly new to docker,
regular crontab -e opens the host crontab = useless 

volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    - ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    #- ./data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    #- ./modules:/www/html/Modules
    - ./logs/:/www/logs
    - ./assets:/assets - mounted this volume inside docker-compose still no luck

**Comment by aj-saini** [comment]
@BrianGilbert any luck update
