### ISSUE TITLE
Module update breaks container. Module files all disappear.

### ISSUE THREAD

**Issue by ThatBrownGuy35** [tiredofit/docker-freescout#101]
### Summary

Updating any module results in Production.ERROR.

[2022-12-13 09:19:51] production.ERROR: Class "Modules\Checklists\Providers\ChecklistsServiceProvider" not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class \"Modules\\Checklists\\Providers\\ChecklistsServiceProvider\" not found at /www/html/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:279)
[stacktrace]

All the module files under \modules disappear. 

### Steps to reproduce

Updating the modules or modifying the .yml file results in the same error. 

Clearing the cache or updating the DB does not resolve the issue

Any help would be appreciated.

**Comment by tiredofit** [comment]
Can you tell me what Freescout Version and the output of your `image_version` command inside the container?

Freescout image updated by default to PHP 8.2 today along with Freescout 1.8.39 and you may need to change your PHP version, I build for `7.4` `8.0` 8.1` `8.2`

**Comment by ThatBrownGuy35** [comment]
Image: /assets/.changelogs/tiredofit_docker-alpine.md 7.7.33
Image: /assets/.changelogs/tiredofit_docker-freescout.md 1.16.2
Image: /assets/.changelogs/tiredofit_docker-nginx-php-fpm.md 7.2.1
Image: /assets/.changelogs/tiredofit_docker-nginx.md 6.2.9

PHP 8.1.13 (cli) (built: Nov 23 2022 13:29:46) (NTS)
Copyright (c) The PHP Group

**Comment by tiredofit** [comment]
Alright you are fairly recent but this is not releted to PHP 8.2 

Hows about posting your (sanitized) docker-compose.yml file or how you are launching the image?

**Comment by ThatBrownGuy35** [comment]
launching the image using docker-compose up -d && docker-compose logs -f

version: '2'

services:
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    ports:
    - 8080:80
    links:
    - freescout-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    #- ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    - ./data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    - ./modules:/www/html/Modules
    - ./logs/:/www/logs
    - ./ldap.conf:/etc/openldap/ldap.conf:ro
    environment:
    - CONTAINER_NAME=freescout-app

    - DB_HOST=freescout-db
    - DB_NAME=freescout
    - DB_USER=freescout
    - DB_PASS=
    - SITE_URL=
    - ADMIN_EMAIL=
    - ADMIN_PASS=
    - ENABLE_SSL_PROXY=FALSE
    - DISPLAY_ERRORS=FALSE
    - TIMEZONE=America/Vancouver
    restart: always

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=
      - CONTAINER_NAME=freescout-db
    restart: always
    ports:
    - 6044:3306

  freescout-db-backup:
    container_name: freescout-db-backup
    image: tiredofit/db-backup
    links:
     - freescout-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - CONTAINER_NAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    restart: always

**Comment by tiredofit** [comment]
Looks as if you are using both `/data` and `/www/html/Modules` as volume exports which is clobbering each other. - You should use one or the other - I'd recommend only using `/data` as then image upgrades will work properly, unless you have a reason to maintain the freescout source code.

Let me know if that works.

**Comment by ThatBrownGuy35** [comment]
That did the trick. Thank you.

On a side note: - ./ldap.conf:/etc/openldap/ldap.conf:ro points to my ldap.conf. Do you have an example ldap.conf file? I'm trying to get auth working to my AD but there is very limited documentation for it.

**Comment by tiredofit** [comment]
You would only want to use an ldap.conf for the openldap client, the Freescout application sets all of its LDAP parameters within the application. 

I haven't touched an AD forest for almost a decade now, so I'm not sure exactly what to add - I do remember the applications dn's filters being something that I hadn't encountered before and I've worked with LDAP and its bigger brother since the early 90s
