### ISSUE TITLE
Request: Add DB_PGSQL_SSLMODE .env variable.

### ISSUE THREAD

**Issue by Aegis8** [tiredofit/docker-freescout#103]
Hello again.

I filed a request, https://github.com/freescout-helpdesk/freescout/issues/2485, to add the option of setting the pgsql sslmode. This was implemented on the Master branch: DB_PGSQL_SSLMODE

Can this env variable be added to the image, please?

I am snowed under at the moment but will try and get a PR created when I have some time.

**Comment by tiredofit** [comment]
Sure! Has been added in `1.16.13` - Stay warm.

**Comment by Aegis8** [comment]
Great! Thank you!
