### ISSUE TITLE
Docker Image Vulnerabilities (Critical)

### ISSUE THREAD

**Issue by deleston** [tiredofit/docker-freescout#108]
### Summary

Docker images have vulnerabilities (critical& hight findings)

### Steps to reproduce

1. docker pull tiredofit/freescout (pull image from official repo)
2. AWS CLI login (login into AWS account for uploading image into ECR)
3. Docker tag (Tag your image)
4. Docker push (Pushed tagged imaged into ECR)
5. Lookup Enhanced Scanning on AWS ECR

### What is the expected *correct* behavior?

Shouldn't have critical or high vulnerabilities

### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/95869819/215752666-e274c44a-46a3-4c27-bd61-44afd7d05463.png)

### Environment

- Image version / tag:   docker pull tiredofit/freescout:latest
- Host OS: Linux

    
### Possible fixes

Update laravel/framework package and symfony/ http-foundation

**Comment by tiredofit** [comment]
Thanks. Not sure I can do anything about this as this is related to the freescout codebase and all I am is a Docker image packager.

**Comment by deleston** [comment]
Oh, Ok

Thank you
