### ISSUE TITLE
Wrong php version, shoudl be

### ISSUE THREAD

**Issue by mbl72** [tiredofit/docker-freescout#123]
### Summary

We're using this docker image : FreeScout, version: php8.2-1.16.34

### Steps to reproduce

System status inside Freescout show PHP 8.1.16.

And just to be sure, I loggen on via the terminal, and here I verified that it is indeed using 8.1.16

`root@freescout-u1149:~# docker container exec -it freescout-app /bin/bash`
`[tiredofit/freescout:1.16.34 12:44:11 /] $ php --version`
`**PHP 8.1.16 (cli) (built: Feb 15 2023 18:27:15) (NTS)**`
`Copyright (c) The PHP Group`
`Zend Engine v4.1.16, Copyright (c) Zend Technologies`
`    with Zend OPcache v8.1.16, Copyright (c), by Zend Technologies`

### What is the expected *correct* behavior?

Php 8.2 should be used.

### Environment

- Image version / tag:  
- Host OS:

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>

    
### Possible fixes
Seems as the image is build with a wrong version of Php

**Comment by tiredofit** [comment]
Thanks, to look into - my build scripts might have gone haywire.

**Comment by tiredofit** [comment]
Confirmed - All images building as PHP 8.1

**Comment by mbl72** [comment]
Thanks for a quick response 👏👏

I can confirm that the issue is resolved
