### ISSUE TITLE
Incorrect Time Zone

### ISSUE THREAD

**Issue by lawfulsoftware** [tiredofit/docker-freescout#124]
I am running 1.8.69 using the PHP 8.2 version (:latest).  I have used several of the latest versions.

I have the env variable TIMEZONE set to America/Vancouver.  It seems to detect this when booting the container because it outputs:

Image:  tiredofit/freescout | Version  1.16.39 Type 'image_changelog' for details
Repository/Issues/Support:  https://github.com/tiredofit/docker-freescout/
           Sponsor me for development and upkeep: https://www.tiredofit.ca/sponsor
2023-03-23.15:52:42 [NOTICE] ** [timezone] Timezone: Setting to 'America/Vancouver' from 'Etc/GMT'

However the config file on the server ends us America/Los_Angeles and America/Los_Angeles (GMT-0700) appears in the System Status page.

**Comment by tiredofit** [comment]
Technically they are still the same - but I agree that they are different, that was a decision on the freescout developers, where I am following the Unix timezones..

**Comment by tiredofit** [comment]
Agreed - I've been rooting for a change for many years - the spring one seems to be getting harder and harder for me each year.
