### ISSUE TITLE
Modules Deleted When Recreating Container

### ISSUE THREAD

**Issue by lawfulsoftware** [tiredofit/docker-freescout#125]
Perhaps I am doing something incorrectly.  I have a Docker Compose stack that appears to be working correctly.  I can install and activate modules however, when I recreate the container, it will often throw an error:

Modules Issue: Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class "Modules\ApiWebhooks\Providers\ApiWebhooksServiceProvider" not found

I see this appear in while the container is booting up.  I don't know if it eventually fixes itself or if, after trying dozens of times to recreate the container, it pushes past the problem and I can actually see the UI instead of an error message.  I then have an issue where I cannot click on Mailbox, Manage, or my Profile.  This also seems to resolve after a time.  Each of the modules then shows as inactive.  I have to manually uninstall each module, re-enter its licence key (thankfully it is prefilled), and re-activate it.

**Comment by tiredofit** [comment]
This could happen if you are not exporting any volumes, particularly `/data` .

**Comment by tiredofit** [comment]
I would just let `.../data:/data` do the work and omit your second line regarding modules. I believe this may be breaking the "persistence" that I envisioned and clobbering each other with their own set of symbolic links. 

Logs I would also keep, as they are useful long term.
