### ISSUE TITLE
migrations not running

### ISSUE THREAD

**Issue by saty9** [tiredofit/docker-freescout#13]
I was struggling to get imap emails setup and enabled errors to see that the sql table was missing columns i tried going into the container and running 
````
php artisan migrate 
````
but received these errors:

````
In AbstractMySQLDriver.php line 115:

  An exception occurred while executing 'SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COL
  UMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS Cha
  racterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'freescout' AND TABLE_N
  AME = 'send_logs'':

  SQLSTATE[HY000]: General error: 1036 Table '/tmp/#sql_437_0.MAI' is read only


In PDOConnection.php line 106:

  SQLSTATE[HY000]: General error: 1036 Table '/tmp/#sql_437_0.MAI' is read only


In PDOConnection.php line 104:

  SQLSTATE[HY000]: General error: 1036 Table '/tmp/#sql_437_0.MAI' is read only
````

**Comment by tiredofit** [comment]
Strange, what version are you running? Have you been running the image for a while?
What's your Host OS and filesystem?

**Comment by saty9** [comment]
I was running 1.1.5 before attempting upgrade I think. But in one of my attempts I deleted the mounted database to see if that would let it create an up to date DB to start with(I kept a backup) I did this test on your latest image v1.3.(5?) of freescout.

Host os is Ubuntu ext4 filesystem.

**Comment by tiredofit** [comment]
Sorry about the delay. I did notice quite a few errors on how I was handling auto upgrades and it was ugly. I have refactored the image over the past few days and it seems I've ironed out most of the bugs. I ran into quite the mess trying to make sure that the .env file APP_KEY wasn't getting overwritten often (it was deleting my passwords in app), and also had to reverse engineer how Modules are actually installed. Hopefully this resolves it for you!

**Comment by saty9** [comment]
Hi Ive tried pulling new copies of all my images but still having no luck running migrations (having to do it manually as pulling freescout image updated it without changing db still getting the same issue with tmp files not being writeable by the database

**Comment by tiredofit** [comment]
OK. Thanks for this. 
How do you have this installed:
Are you exporting /www/html ?
Or are you just exporting /data (leaving freescout sourcecode original and letting the image dynamically create the config each startup).

I have a routine that looks for something called .freescout-version if doing the /data method which bases it on the original install, upgraded install, and upgraded image value which executes the migrations, however I think there may be an issue if you are going down the /www/html route. I'm going to have to think about how to solve that, I don't _think_ it will cause any problems if we attempt to migrate every container startup, but I'll need some testing on this. 

The /tmp problem where you can't write to that folder i am at a loss - I cann't reproduce that on my own system, I'm wondering if we can try creating a folder called tmp outside of your container, mapping it via volumes, and making sure its set as chmod 777.

**Comment by tiredofit** [comment]
Also, when inside the container, can you try padding your artisan commands with: 
`sudo -u nginx`

ie `sudo -u nginx php artisan <command>`

I'll add a shortcut in next release to avoid having to do this.

**Comment by saty9** [comment]
ive been using a docker compose file:
version: '2'

services:
  
  freescout-app:
    image: tiredofit/freescout:latest
    container_name: freescout-app
    links:
    - freescout-db
    volumes:
    - ./logs/:/www/logs
    environment:
    - VIRTUAL_HOST=*******
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=***********
    - LETSENCRYPT_EMAIL=*************

    - ZABBIX_HOSTNAME=freescout-app
    
    - DB_HOST=freescout-db
    - DB_NAME=freescout
    - DB_USER=freescout
    - DB_PASS=freescout

    - SITE_URL=https://*********
    - ADMIN_EMAIL=***********
    - ADMIN_PASS=*************
    - ENABLE_SSL_PROXY=TRUE
    - DISPLAY_ERRORS=TRUE
    - TIMEZONE=Europe/London
    ports:
      - "5050:80"
    restart: always

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=freescout
      - MYSQL_USER=freescout
      - MYSQL_PASSWORD=freescout

      - ZABBIX_HOSTNAME=freescout-db
    restart: always

  freescout-db-backup:
    container_name: freescout-db-backup
    image: tiredofit/db-backup
    links:
     - freescout-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - ZABBIX_HOSTNAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    restart: always

this is then behind an nginx reverse proxy I'll try the modified artisan command just now

**Comment by saty9** [comment]
same error with the 
sudo -u nginx php artisan migrate

**Comment by tiredofit** [comment]
Have a go at this docker-compose example. You should be able to reuse your existing DB so just update the credentials properly or just replace out the freescout-app service with what I've put in and let's see if this solves anything. This will solve some of the issues I've been seeing with data persistence, encryption keys, and should also enable the automatic migrations support.

````bash
version: '2'

services:
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    ports:
      - 5050:80
    links:
      - freescout-db
    volumes:
      - ./data:/data
      - ./logs/:/www/logs
    environment:
      - ZABBIX_HOSTNAME=freescout-app
    
      - DB_HOST=freescout-db
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout

      - SITE_URL=https://***
      - ADMIN_EMAIL=***
      - ADMIN_PASS=***
      - ENABLE_SSL_PROXY=TRUE
      - DISPLAY_ERRORS=TRUE
      - TIMEZONE=Europe/London
    restart: always

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=password
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout

      - ZABBIX_HOSTNAME=freescout-db
    restart: always

  freescout-db-backup:
    container_name: freescout-db-backup
    image: tiredofit/db-backup
    links:
     - freescout-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - ZABBIX_HOSTNAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    restart: always
````

**Comment by saty9** [comment]
new error on running migrate:
The stream or file "/www/html/storage/logs/laravel-2019-12-11.log" could not be opened: failed to open stream  
  : Permission denied

**Comment by saty9** [comment]
that error goes back to the normal one about tmp files if I dont use the sudo -u nginx prefix

**Comment by tiredofit** [comment]
Do you by chance have portainer or anything running or we can join in on a way for you to share your screen/let me poke around your container? This seems very odd.

**Comment by saty9** [comment]
yes but it will take me a while to isolate the system I will get back once I have

**Comment by tiredofit** [comment]
No worries. Feel free to contact me with the email address in the changelog.

**Comment by tiredofit** [comment]
Solved Privately - Problem with DB Image (tiredofit/mariadb) - Fixed privately
