### ISSUE TITLE
No Database Host Entered! - Set '$DB_HOST'

### ISSUE THREAD

**Issue by 24junk** [tiredofit/docker-freescout#131]
### Summary

After pulling the latest release docker-compose starts up with an error that halts freescout-app.
Nothing was modified in docker-compose.yml prior to this update image step.

### Steps to reproduce

1) docker-compose down
2) docker pull tiredofit/freescout
3) docker-compose up

### What is the expected *correct* behavior?

Before this  release every step went fine.

### Relevant logs and/or screenshots
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/1134583/234914833-262a12ae-d89a-41b9-b47d-0992f8c2906b.png">

### Environment

- Image version / tag:  latest
- Host OS: Ubuntu 20.04.6 LTS

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>

**Comment by Raito00** [comment]
The same case?
#
Pulling freescout-db-backup (tiredofit/db-backup:)...
ERROR: manifest for tiredofit/db-backup:latest not found: manifest unknown: manifest unknown
#

**Comment by marek94901** [comment]
Same problem. PHP8.2 - 1.17.1

![obrázok](https://user-images.githubusercontent.com/86384456/234943424-278246e3-cbf9-49f9-b9e4-c2dc09df3652.png)

**Comment by tiredofit** [comment]
Replacement images have been built in the correct sequence. Let me know if this works..

**Comment by 24junk** [comment]
Dave, everything worked as expected! Thanks for fixing :)
