### ISSUE TITLE
Customer receives email with original customer name despite customer change

### ISSUE THREAD

**Issue by lucollab** [tiredofit/docker-freescout#136]
Hello all,

if I change the email address of the customer in an open ticket, the first and last name (display name) of the previous customer remains, even if the email changes.

So if I have a ticket open from the customer "Ben Wight" with the email address "ben.wight@mail.com" in which "Mona Wight" is in CC with "mona.red@mail.com" and I want to send a reply in the ticket to "Mona Red", I click on the reply button and select "mona.red@mail.com". In FreeScout this all looks neat and correct.

In the mail client of "Mona Red", however, an e-mail comes in with the following recipient: "Ben Wight <mona.red@mail.com>".

Is this a deliberate behaviour or a bug?

Many thanks for your help!

Best regards
Lukas

**Comment by tiredofit** [comment]
This would be best for the actual [freescout repository](https://github.com/freescout-helpdesk/freescout). I'm just a lowly Docker image. If your issue turns out to be the image, then I'll gladly fix.
