### ISSUE TITLE
Reply on one element in a ticket

### ISSUE THREAD

**Issue by lucollab** [tiredofit/docker-freescout#137]
Hello all,

is there a possibility in FreeScout to only reply to a ticket post in a ticket?

Example: If I have a ticket that concerns several customers, I also receive several replies from the different customers in this ticket. A typical example is a collective ticket. If I now want to answer only one customer's answer in this collective ticket, I need a possibility to answer a single item in the series of this ticket.

Does such a possibility exist? Possibly through a module?

Many thanks in advance,
With best regards
Lukas

**Comment by tiredofit** [comment]
This would be best for the actual [freescout repository](https://github.com/freescout-helpdesk/freescout). I'm just a lowly Docker image. If your issue turns out to be the image, then I'll gladly fix.
