### ISSUE TITLE
Recommend to persist user storage

### ISSUE THREAD

**Issue by silviot** [tiredofit/docker-freescout#14]
Freescout stores user profile pictures in `/www/html/storage/app/public/users/`.

In case this path is not mounted and the container is recreated, the pictures are lost.

To prevent this the `/www/html/storage/app` should be mounted as a persistent volume. The documentation does not currently mention this. `/www/html` is mentioned as an optional mount only if you need self-updating.

I'm not very familiar with Freescout, but I'm afraid it might store more vital information there too.

**Comment by tiredofit** [comment]
Hi there, I handle the folder persistence for that folder and others by having the user map /data. Let me know if that gives you the profile photos after restarting the container.
