### ISSUE TITLE
Wrong version?

### ISSUE THREAD

**Issue by Henkka80** [tiredofit/docker-freescout#144]
Hi have anyone else installed newest version? Did it upgrade the Freescout to correct version.

For me it didnt update.

So 1.17.19 (latest)
says that it uses: 
- Freescout 1.8.89

If you check zip file, you can see in Dockerfile:
ENV FREESCOUT_VERSION=${FREESCOUT_VERSION:-"1.8.86"} \

So is it typo, or did i made some mistake?

**Comment by tiredofit** [comment]
It looks like my upstream git server is not synchronizing properly to github. I have just reestablished the link so builds will be accurate now..

**Comment by Henkka80** [comment]
Perfect, now it works correctly.

Thanks for great support.
