### ISSUE TITLE
ARM Architecture Support for tiredofit/mariadb

### ISSUE THREAD

**Issue by leadvic** [tiredofit/docker-freescout#148]
**Description of the feature**
I'd love to see the image tiredofit/mariadb supported for ARM architecture, in my understanding this might not be that hard as mariadb itsefl has support for ARM.

**Benftits of feature**
This would be great for new users who might want to try the docker compose on their ARM computers to avoid issues where the tiredofit/freescout and tiredofit/db-backup work just fine and the tiredofit/mariadb which is really important doesn't have support for it.

**Comment by tiredofit** [comment]
`tiredofit/mariadb:10.11` now works for armv8 / arm64 processors...
