### ISSUE TITLE
Tags enabled mail box give whoops

### ISSUE THREAD

**Issue by MathijsA** [tiredofit/docker-freescout#15]
When I updated the docker to Freescout version 1.4.11 i could activate the tags module. After is was activated my mailbox didden't work and gave "whoops, an error occurred". I don't know if this is an error in the docker container or of freescout it self?

**Comment by tiredofit** [comment]
Try restarting the container if you can.  Sometimes the Database migrations don't run properly after activation and cause this to occur. Let me know if this solves.

**Comment by MathijsA** [comment]
Yes that fixed it thank you very much.

**Comment by tiredofit** [comment]
Great. If you ever run into this again and don't want to restart the container, head inside and execute this:
`sudo -u ${NGINX_USER} php artisan migrate --no-ansi` and answer yes to any of the questions. I'm doing it automatically on each container start, but sometimes as you noticed some of the migrations don't run automatically on module install. I also believe there is a way to execute the migrations from the Admin -> Settings section.

**Comment by MathijsA** [comment]
Thank you for the extra info. i'll keep it in the back off my mind. restarting the docker is no problem for us.
