### ISSUE TITLE
LDAP module in docker installation not working

### ISSUE THREAD

**Issue by Azziii** [tiredofit/docker-freescout#155]
I am using an installation using Docker (php7.4-1.17.40) and the "LDAP Integration" module (1.0.30). After activating the module and entering the necessary settings, the "Connect & Fetch Attributes" button worked successfully. Specified the following parameters:
E-mail -> mail
First Name -> given name
Last Name -> sn
Job Title -> title
Phone Number -> telephonenumber

After that, I set "DNs and Filters"
dc=domain,dc=local(objectclass=person)

I chose "Automatic Import" and "LDAP Authentication" and saved the settings. But the "Import Now" button remained inactive and the import of users did not occur. I cleared the cache, deactivated-activated the module, restarted the module - nothing helped.
It turned out to go inside the container and execute "/www/html # php artisan adldap:import". But LDAP Authentication and automatic import do not work. When creating a ticket, imported users cannot be selected. What else do I need to configure?

**Comment by tiredofit** [comment]
You may want to get support from the Freescout developers on the module. In production usage the module and this image is working fine, so I can't support an image issue..

You may want to look at your logs of your LDAP server and troubleshoot your connectivity that way..
