### ISSUE TITLE
Added a community module but permissions not working

### ISSUE THREAD

**Issue by iantearle** [tiredofit/docker-freescout#159]
### Summary

Installed https://github.com/avenjamin/freescout-Themes-Module and followed the instructions. Altered permissions but still getting a permissions error when the module tries to save the files.

### Steps to reproduce

Install the above module, change a color in the theme settings. 

### What is the expected *correct* behavior?

Color should alter to selected. 

### Relevant logs and/or screenshots

 file_put_contents(/www/html/Modules/Themes/Providers/../Public/css/module.css): Failed to open stream: Permission denied {"userId":1,"email":"name@name.com","exception":"[object] (ErrorException(code: 0): file_put_contents(/www/html/Modules/Themes/Providers/../Public/css/module.css): Failed to open stream: Permission denied at /www/html/Modules/Themes/Providers/ThemesServiceProvider.php:110)

### Environment

Ubuntu 22 EC2 instance

### Possible fixes

I am guessing the chown permissions are not correct, the module suggests www-data - I have tried the current user ubuntu and root to no avail.
Is there a specific usergroup for the docker container?

**Comment by tiredofit** [comment]
Restarting the container should usually reset it to the proper permissions however you can:

From inside container: `chown -R ${NGINX_USER}:${NGINX_GROUP} <moduledir>`
From outside container: `chown -R 80:82 <moduledir>`

**Comment by iantearle** [comment]
80:82 who knew. Thank you. That did it perfectly.
