### ISSUE TITLE
storage/logs/ owned by root

### ISSUE THREAD

**Issue by MathijsA** [tiredofit/docker-freescout#16]
after a new pull form the image the folder /data/storage/logs/ is owned by root nd not by ngnix:www-data as it should be.

**Comment by tiredofit** [comment]
OK, to look into today. What version were you coming from?

**Comment by MathijsA** [comment]
from freescout 1.5.2 -> 1.5.2 docker version 1.7.3 if iam not mistaken

**Comment by tiredofit** [comment]
Thanks. Will look into today. Have a couple things ahead of it, but should get to before close of day.

**Comment by tiredofit** [comment]
New build incoming that forces reset of permissions on each container restart. Docker Hub is lagging a bit. 1 - 2 days max.
