### ISSUE TITLE
Fails auto fetching IMAP only without errors.

### ISSUE THREAD

**Issue by SyberSin** [tiredofit/docker-freescout#167]
Hello,

Just got FreeScout setup on Unraid with the official docker image. Everything is working with zero errors in the logs, except fetching emails automatically with IMAP does not work. I have connected other services to this email account through IMAP without issues.

The cron job shows it connects, finds mailboxs and folders, but fetches zero new emails when there are new emails to be fetched.

If I do a manual fetch by running `php artisan schedule:run` or `freescout:fetch-emails` it does the same thing, runs without errors but fetches nothing.

The strangest part is that if I do a manual fetch with the built in system tool it DOES grab all the new emails with no issues or errors. So, my IMAP connection must be correct.

Also, if I change the email account type to POP, everything works fine, including the cron job, it fetches new emails without issue. It's only the cron fetching of IMAP that is not working. Again, not a single error is in the logs, all this leaves me to believe it is an issue with FreeScout.

This is the only thing preventing me from converting to FreeScout and purchasing a bunch of the modules.

The email account is hosted in cpanel from NameCheap. Default email setup. I have checked all credentials a hundred times, and tried with and without ssl, and have read through the documentation on here multiple times and have tried everything recommended without success.

Any help would be greatly appreciated.

- FreeScout version: 1.8.117
- Database: PostgreSQL
- Image version / tag:  freescout:latest
- Host OS: Unraid

**Comment by tiredofit** [comment]
Log files might give some insight as to what is happening, specifically the laravel.log file inside the container.

Otherwise `APP_NEW_FETCHING_LIBRARY=TRUE` may work out for you. 

Anything more would go outside of this Docker image and would need to be reported to the upstream repo for bug fixing as this is just strictly focusing on the Docker image..

**Comment by SyberSin** [comment]
Thank you for the reply. 

Attached is the log. 

I added the variable, and it did not appear to do anything.

[laravel-2024-01-16.log](https://github.com/tiredofit/docker-freescout/files/13957411/laravel-2024-01-16.log)
