### ISSUE TITLE
ngnix conf wrong attachment localtion

### ISSUE THREAD

**Issue by MathijsA** [tiredofit/docker-freescout#17]
In /etc/ngnix/conf.d/default.conf is the wrong location

This is what is should 

```
location ^~ /storage/app/attachment/ {
    internal;
    alias /www/html/storage/app/attachment/;
}
```

**Comment by tiredofit** [comment]
OK I believe I had it at that at the very beginning but based on this thread https://github.com/freescout-helpdesk/freescout/issues/522#issuecomment-596923374 (and the lead developer contacting me privately alerting me of this) I switched it to this. What are you seeing with this configuration in place?

**Comment by MathijsA** [comment]
It was something like '/var/www...' but the www-folder is in '/' and not i 'var'.
With the code link above it works.

**Comment by tiredofit** [comment]
OK, I've updated it to the path as per your request in version `1.7.5` - Docker Hub is building and should be there by end of day.

**Comment by MathijsA** [comment]
Thanks a lot
