### ISSUE TITLE
Freescout IMAP connection error - SMTP is connecting

### ISSUE THREAD

**Issue by semaf** [tiredofit/docker-freescout#173]
Hey,

I have an issue with the IMAP connection with type of encryption. SMTP is working fine. It is a local connection between two docker containers in same network. Would be about some help.

If using STARTTLS, the log:
`Apr 26, 15:30:02 Error fetching email Error: connection failed; File: /www/html/overrides/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php (82)`

Dovecot log:
`dovecot-mailcow-1  |  dovecot: imap-login: Disconnected: Aborted login by logging out (auth failed, 1 attempts in 3 secs): user=<domain>, method=PLAIN, rip=172.22.1.16, lip=172.22.1.250, TLS, TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)`

Using TLS, the log
`Apr 26, 15:30:02 Error fetching email Error: connection failed; File: /www/html/overrides/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php (82)`

Dovecot:
`dovecot-mailcow-1  | dovecot: imap-login: Disconnected: Too many invalid commands (no auth attempts in 0 secs): user=<>, rip=172.22.1.16, lip=172.22.1.250`

Using none encryption:
`Apr 26, 15:34:04 | Error fetching email | Error: connection setup failed; File: /www/html/vendor/webklex/php-imap/src/Client.php (391)`

Dovecot:
`dovecot-mailcow-1  | dovecot: imap-login: Disconnected: Aborted login by logging out (auth failed, 1 attempts in 0 secs): user=<domain>, rip=172.22.1.16, lip=172.22.1.250`

**Comment by tiredofit** [comment]
This would be better posed in the actual [Freescout](https://github.com/freescout-helpdesk/freescout) code repository. If it turns out to be a Docker related issue I will gladly fix but this seems either configuration related or IMAP library related which I deem as upstream.
