### ISSUE TITLE
When two users are on the same conversation they swap users.

### ISSUE THREAD

**Issue by alexskrms** [tiredofit/docker-freescout#176]
### Summary

Hi, I have found a bug that has been happening a long time for me but I hoped it would be fixed so now I open an Issue to let the community know about it. The bug is related when two users are in the same conversation one of them receives a popup of "lost internet connection". After that, if they refresh the page they are converted to the other user that was watching the conversation too. After that, if now with the converted user, you log out and enter with yours, when you log out you also kick the other person out of their user.

### Steps to reproduce

It simply happens when two people are in a conversation and you can test scrolling or changing status to try to force it even faster.

### What is the expected *correct* behavior?

Not to swap to another user and just stay with yours while other people can see the conversation too.

### Environment
Client: Docker Engine - Community
 Version:           25.0.4
 API version:       1.44
 Go version:        go1.21.8
 Git commit:        1a576c5
 Built:             Wed Mar  6 16:32:12 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.4
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       061aa95
  Built:            Wed Mar  6 16:32:12 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- Image version / tag: tiredofit/freescout:latest
- Host OS: Ubuntu 22.04

**Comment by sparker81** [comment]
Are you running NGINX Proxy Manager by chance?

**Comment by alexskrms** [comment]
> @alexskrms are you running NGINX Proxy Manager by chance?

Yes @sparker81

**Comment by sparker81** [comment]
You will need to turn off the Cache Assets setting if you have it turned on for Freescout in NGINX Proxy Manager. I had to find that out the hard way. https://github.com/freescout-helpdesk/freescout/issues/3837

**Comment by sparker81** [comment]
Here's a screenshot. Hopefully it fixes the issue.

![RemoveCacheAssets](https://github.com/tiredofit/docker-freescout/assets/102618401/7925d33f-facc-4a37-97d6-da3851b7e6fb)

**Comment by alexskrms** [comment]
> Here's a screenshot. Hopefully it fixes the issue.
> 
> ![RemoveCacheAssets](https://private-user-images.githubusercontent.com/102618401/330868523-7925d33f-facc-4a37-97d6-da3851b7e6fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNDk3NzYsIm5iZiI6MTcxNzA0OTQ3NiwicGF0aCI6Ii8xMDI2MTg0MDEvMzMwODY4NTIzLTc5MjVkMzNmLWZhY2MtNGEzNy05N2Q2LWRhMzg1MWI3ZTZmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQwNjExMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjZmMjIxYTU0OWE0OGVkZDk3YTg0Y2ZiMTM5M2JkYjg2NjZjYTYxNGFmYjM2ZGE1NjAwOWJlNjc5MDRkODZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EYHJGZ5BC-kEaDOdFHFltvuojqK_dOcq3tvDyGaKyBk)

Thanks you soo much solved!
