### ISSUE TITLE
Version 1.17.70 => Freescout 1.8.133

### ISSUE THREAD

**Issue by mixmix99** [tiredofit/docker-freescout#177]
### Summary
I am using the docker "latest" tag and need a bugfix in Freescout version 1.8.139, but in the "latest" or "php8.3-1.17.70" tag contains the version 1.8.133. 

### Steps to reproduce

Nothing special, just pulled the "latest" or "php8.3-1.17.70" tagged image.

### What is the expected *correct* behavior?

Should contain Freescout version 1.8.139 

### Relevant logs and/or screenshots

![image](https://github.com/tiredofit/docker-freescout/assets/11771019/df050596-8346-4031-a327-ded7cac92b46)

### Environment

- Image version / tag:  "latest" or "php8.3-1.17.70"
- Host OS: Ubuntu 23.10
<details>
<summary>
docker-compose.yaml
</summary>
services:
  freescout-app:
    image: tiredofit/freescout:latest
    container_name: freescout-app

....
</details>

**Comment by gerbenvandekraats** [comment]
Same problem over here!

**Comment by tiredofit** [comment]
Sorry about this, looks like I messed up the releases the other night. Latest or `1.17.71` now contains 1.8.139.

**Comment by gerbenvandekraats** [comment]
Yes got it running at 1.8.139 now! Thanks for this super fast fix 👍

**Comment by mixmix99** [comment]
Now everything is as it should be. Thank you for that very quick fix!
