### ISSUE TITLE
Uncapitalized Freescout in page title

### ISSUE THREAD

**Issue by freescout-helpdesk** [tiredofit/docker-freescout#181]
### Summary

One user noticed that the name of the app is not capitalized: https://github.com/freescout-helpdesk/freescout/issues/4048

It must be because of this line: https://github.com/tiredofit/docker-freescout/blob/main/install/assets/defaults/30-freescout#L5

**Comment by tiredofit** [comment]
Thanks for the investigation - That would do it, I've been calling it Freescout for years, have now adjusted to FreeScout. Fixed in `1.17.73` https://github.com/tiredofit/docker-freescout/commit/0ad08637bbb7390eea42f894744c2ad3366312bc
