### ISSUE TITLE
Does not create ANY tables on install

### ISSUE THREAD

**Issue by scottcaseproof** [tiredofit/docker-freescout#191]
### Summary

Brand new install using docker image and no tables are created in the database, resulting in an error when trying to login

### Steps to reproduce

Install via docker-compose with the no proxy example file. Try to login and receive this error:
`Whoops, looks like something went wrong — check logs in /storage/logs`

Check logs and see this:
`[tiredofit/freescout:1.17.88 14:40:45 /www/html/storage/logs] $ cat fetch-emails.log 

In Connection.php line 664:
                                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'username'@'172.19.0.4' (usi  
  ng password: YES) (SQL: select * from `options` where (`name` = fetch_email  
  s_last_run) limit 1)                                                         
                                                                               

In Exception.php line 18:
                                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'username'@'172.19.0.4' (usi  
  ng password: YES)                                                            
                                                                               

In PDOConnection.php line 38:
                                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'username'@'172.19.0.4' (usi  
  ng password: YES)                                        `

Check Database for tables and get this:
`MariaDB [freescout]> show tables;
Empty set (0.000 sec)`

Without any tables, especially a users table, no one can login.

### What is the expected *correct* behavior?

Tables should be created correctly, and a user should be able to login.

### Environment
docker-compose.yml (usernames, passwords, email, and ip has been changed)
`version: '2'

services:
  
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    ports:
    - 8080:80
    links:
    - freescout-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    - ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    #- ./data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    - ./modules:/www/html/Modules
    - ./logs/:/www/logs
    environment:
    - CONTAINER_NAME=freescout-app
    - DB_HOST=freescout-db
    - DB_NAME=freescout
    - DB_USER=username
    - DB_PASS="vny589pnvtym859eivnym59gtu"
    - SITE_URL=http://xxx.xxx.xxx.xxx:8080
    - ADMIN_EMAIL=test@test.com
    - ADMIN_PASS="cnty547entcym87ocwernghiu"
    - ENABLE_SSL_PROXY=FALSE
    - DISPLAY_ERRORS=FALSE
    - TIMEZONE=America/Denver
    restart: always

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS="ctyn784eonctyo87weghigd"
      - DB_NAME=freescout
      - DB_USER=username
      - DB_PASS="vny589pnvtym859eivnym59gtu"
      - CONTAINER_NAME=freescout-db
    restart: always

  freescout-db-backup:
    container_name: freescout-db-backup
    image: tiredofit/db-backup
    links:
     - freescout-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - CONTAINER_NAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=freescout
      - DB_USER=username
      - DB_PASS="vny589pnvtym859eivnym59gtu"
      - DB01_BACKUP_INTERVAL=1440
      - DB01_BACKUP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    restart: always`

**Comment by tiredofit** [comment]
Remove the Double quotes on the *_PASS variables..

**Comment by scottcaseproof** [comment]
I threw those in because it refused to connect to the database without them, but for some reason it workede just fine this time. Thanks!!
