### ISSUE TITLE
Enable posix PHP extension

### ISSUE THREAD

**Issue by RisingOpsNinja** [tiredofit/docker-freescout#198]
Install and enable the [posix PHP extension](https://www.php.net/manual/en/book.posix.php)

**Benefits of feature**

The posix extension is  used by many dependencies if it is available.

E.g. the [LDAP integration module ](https://freescout.net/module/ldap/)had recently a related bug if it is missing:

>      1.0.38
> 
>     New - Fix an issue with hanging commands executed by cron on servers with disabled \"posix_isatty()\" PHP-function.

Source: https://freescout.net/module/ldap/?changelog=1

**Additional context**

Installing posix is also encouraged in a comment in the Freescout source code:

>   // If posix_isatty() function is not enabled on the server the question in the
     // console command makes it wait infinitely and be aborted.
     // Commands should avoid using interctive functions or use special flags.
     //'posix_isatty (PHP)'  => function_exists('posix_isatty'),

Source: 
https://github.com/freescout-help-desk/freescout/blob/e2360f21464c1a2c459beb3b708f0d8851f7ced8/app/Misc/Helper.php#L1983

List of posix function usage:

 - posix_kill()
 
> vendor/psy/psysh/src/Configuration.php:        $this->hasPcntl    = \function_exists('pcntl_signal') && \function_exists('posix_getpid');
vendor/psy/psysh/src/ExecutionLoop/ProcessForker.php:        return \function_exists('pcntl_signal') && \function_exists('posix_getpid');
vendor/psy/psysh/src/ExecutionLoop/ProcessForker.php:            \posix_kill(\posix_getpid(), SIGKILL);
vendor/psy/psysh/src/ExecutionLoop/ProcessForker.php:        $this->savegame = \posix_getpid();
vendor/psy/psysh/src/ExecutionLoop/ProcessForker.php:                \posix_kill(\posix_getpid(), SIGKILL);
vendor/psy/psysh/src/functions.php:            'posix available' => \function_exists('posix_getpid'),
vendor/monolog/monolog/src/Monolog/SignalHandler.php:                && extension_loaded('posix') && function_exists('posix_getpid') && function_exists('posix_kill')) {
vendor/monolog/monolog/src/Monolog/SignalHandler.php:                    posix_kill(posix_getpid(), $signo);

- posix_isatty()

> vendor/jakub-onderka/php-console-color/src/ConsoleColor.php:            return function_exists('posix_isatty') && @posix_isatty(STDOUT);
vendor/symfony/polyfill-php72/Php72.php:        return \function_exists('posix_isatty') && @posix_isatty($stream);
vendor/symfony/var-dumper/Dumper/CliDumper.php:        if (\function_exists('posix_isatty')) {
vendor/symfony/var-dumper/Dumper/CliDumper.php:            return @posix_isatty($stream);
vendor/symfony/console/Output/StreamOutput.php:        if (\function_exists('posix_isatty')) {
vendor/symfony/console/Output/StreamOutput.php:            return @posix_isatty($this->stream);
vendor/symfony/console/Application.php:        } elseif (\function_exists('posix_isatty')) {
vendor/symfony/console/Application.php:            if (!@posix_isatty($inputStream) && false === getenv('SHELL_INTERACTIVE')) {
vendor/sebastian/environment/src/Console.php:use function posix_isatty;
vendor/sebastian/environment/src/Console.php:        return function_exists('posix_isatty') && @posix_isatty($fileDescriptor);

- posix_getpid()

> vendor/psy/psysh/src/Configuration.php:        $this->hasPcntl    = \function_exists('pcntl_signal') && \function_exists('posix_getpid');
vendor/psy/psysh/src/ExecutionLoop/ProcessForker.php:        return \function_exists('pcntl_signal') && \function_exists('posix_getpid');
vendor/psy/psysh/src/ExecutionLoop/ProcessForker.php:            \posix_kill(\posix_getpid(), SIGKILL);
vendor/psy/psysh/src/ExecutionLoop/ProcessForker.php:        $this->savegame = \posix_getpid();
vendor/psy/psysh/src/ExecutionLoop/ProcessForker.php:                \posix_kill(\posix_getpid(), SIGKILL);
vendor/psy/psysh/src/functions.php:            'posix available' => \function_exists('posix_getpid'),
vendor/monolog/monolog/src/Monolog/SignalHandler.php:                && extension_loaded('posix') && function_exists('posix_getpid') && function_exists('posix_kill')) {
vendor/monolog/monolog/src/Monolog/SignalHandler.php:                    posix_kill(posix_getpid(), $signo);

**Comment by tiredofit** [comment]
`1.17.91` enables Posix, thanks for the deep dive into the code.

**Comment by tiredofit** [comment]
Woops! `1.17.92` spells it right.
