### ISSUE TITLE
Permissions during module development

### ISSUE THREAD

**Issue by thomasplevy** [tiredofit/docker-freescout#202]
### Summary

I am trying to use this repo to build a local development workflow for module development. Right now I can get custom modules installed but I have to update permissions on files or do all my development as root/sudo so I can save changes during development.

I clone my repo and all the files are owned by my host user then after I run `docker compose up` most files get changed to `80:82`. I now can't make changes to existing modules without entering my sudo password. I can create new files but I need to CHOWN them to `80:82` for them to get work in the container.

Thanks

### Environment

- Image version / tag:  1.17.96
- Host OS: Ubuntu 22.04

**Comment by tiredofit** [comment]
It's not entirely apparent in this image - as its a base image feature outlined [here](https://github.com/tiredofit/docker-alpine#permissions)

But `CONTAINER_USER_NGINX=1000` should do it for you.

**Comment by thomasplevy** [comment]
oh man that was easy, thanks so much @tiredofit!
