### ISSUE TITLE
Wiping on Reboot

### ISSUE THREAD

**Issue by Trippik** [tiredofit/docker-freescout#22]
Everytime the docker restarts is wipes the database, treating it as a first time install. Meaning all data is lost with every reboot

**Comment by jugendhacker** [comment]
Maybe you did not mount the db directory ouside of the container like https://github.com/tiredofit/docker-freescout/blob/master/examples/docker-compose.yml#L46 does and so when your restart the container the data is gone?

**Comment by tiredofit** [comment]
DB should already be separate based on my example there isn't any local db server in the image, - I have a feeling that they didn't expose the `/data` folder or any of the folders at all which would certainly delete all data. I built the image to support multiple ways:

a) (recommended) Only hold onto volatile data, ie your own stuff after using the data. Makes it much easier to upgrade the Docker Image and move along with changes of Freescout.

b) Expose the source code which lets you hack away at the code, but makes it more challenging to keep your system up to date.

There is even an enhancement to a) above as well. If you want to hack a few of the files and want them to overwrite the source code, you would simply mount `/assets/custom` and put your files in there to overwrite anything in the /www/html folder. We use that regularly to update files. Even more so you can also mount `/assets/custom-scripts` and it will execute bash scripts in that folder to do work inside the container on each boot. Say for example you want to modify files via `sed` or do something repeatedly, that will also work too.

Regardless, this is stale, so going to close it anyways.
