### ISSUE TITLE
Attachment file size

### ISSUE THREAD

**Issue by tillmon** [tiredofit/docker-freescout#28]
It would be great if attachment file size in configurable. See this issue:

https://github.com/freescout-helpdesk/freescout/issues/721

I cannot find these 2 files:

https://github.com/tiredofit/docker-freescout/blob/2a89068dc0b0223434fdce5a6559844d7c34a1fc/install/etc/nginx/conf.d/default.conf#L43-L44

**Comment by tiredofit** [comment]
Those two files are part of `tiredofit/nginx` base image, and get switched on and modified via environment variables either from that image, or from the `tiredofit/nginx-php-fpm` base image. Your Client body size should already be set to something very liberal like 2G..

**Comment by tillmon** [comment]
I have mixed it up, `client_max_body_size` is related to sending attachments. I had an issue receiving an attachment lager than 10 MB. Do you have any idea would the cause could be?
