### ISSUE TITLE
possibility to add the libxml extension to support the 2FA module

### ISSUE THREAD

**Issue by XtomtomX** [tiredofit/docker-freescout#29]
Hi,
would it be possible to add the libxml extension into the image?
We use the 2FA Module which has this extension as a requirement.

The error thrown in the log is as following:
`You need to install the libxml extension to use this back end {"userId":123,"email":"jane@doe.com","exception":"[object] (BaconQrCode\\Exception\\RuntimeException(code: 0): You need to install the libxml extension to use this back end at /data/Modules/TwoFactorAuth/vendor/bacon/bacon-qr-code/src/Renderer/Image/SvgImageBackEnd.php:46)...`

Regards, Thomas

**Comment by tiredofit** [comment]
Hi Thomas, Yes absolutely.

Can you do me a favour and try adding `PHP_ENABLE_XML=TRUE` to your environment variables and let me know if it works? There are a couple modules we can try to enable but I don't have access to the 2FA module to fully test.

There are other environment variables you can try [here]:(https://github.com/tiredofit/docker-nginx-php-fpm/tree/7.3)

**Comment by XtomtomX** [comment]
Hi,
thank you for the fast response. :)

I checked `PHP_ENABLE_XML=TRUE` which did not worked out (same error). With `PHP_ENABLE_KITCHENSINK=TRUE` it's working. I'll go trough the different settings and will locate the required extension. 

I'll report the required extension after i found the right one.

**Comment by tiredofit** [comment]
Any news on this?

**Comment by XtomtomX** [comment]
Hi sorry for the late reply. We did not further investigated it. We are currently switching over to LDAP Auth and deactivated the 2FA module for now.

We'll check it probably later but atm it's not our top priority. I'll close this issue and will add some additional information if we have the time to further investigate it. :)
