### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by jaydio** [tiredofit/docker-freescout#31]
Should increase memory limit of the php-fpm pool.

`[28-Nov-2020 01:18:18] WARNING: [pool www] child 1534 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 98566192 bytes) in /www/html/vendor/symfony/console/Output/BufferedOutput.php on line 39"`

**Comment by tiredofit** [comment]
`PHP_MEMORY_LIMIT` environment variable will give you what you need.

**Comment by jaydio** [comment]
That worked, thanks! :+1:

I've just noticed the cont-init.d/* files and now have a better understanding of all variables that are exposed.

**Comment by tiredofit** [comment]
Have a peek at the readme's of github.com/tiredofit/docker-alpine / docker-nginx / and docker-nginx-php-fpm - Lots of flexibility
