### ISSUE TITLE
Lost credentials for mailbox and modules

### ISSUE THREAD

**Issue by afawaz2** [tiredofit/docker-freescout#32]
I deployed freescout using a variation of the docker-compose-no-proxy yml file. I configured a mailbox and enabled the LDAP module. When version 1.6.8 came out, I did the following to update to the new version:

docker-compose pull
docker-compose up -d

After the containers started, freescout was at the latest version (1.6.8) however, the passwords stored for the mailboxes were lost and the Ldap module shows as activated but it doesn't show in the settings.

When I deactivated the LDAP module and reactivated it, the module showed in the settings but its stored BIND password was missing.

**Comment by tiredofit** [comment]
Youch. I'm not entirely sure I fully understand how the ldap module works in terms of the user tables but theoretically it shouldn't have deleted anything.

Enter in the container and type 
`artisan freescout:create-user`

It should give you an opportunity to create a new admin user and then go and reactive your modules and get your user tables back.

**Comment by afawaz2** [comment]
It turns out I didn't map the /data volume.
