### ISSUE TITLE
postgres support

### ISSUE THREAD

**Issue by hiaselhans** [tiredofit/docker-freescout#33]
it looks like 'mysql' is hardcoded in the dockerfile.
Can we support other db types like postgres in this container?

https://github.com/tiredofit/docker-freescout/blob/f477098cf232b9d572e1f6868fbefd2232218f69/install/etc/cont-init.d/30-freescout#L180

:)

**Comment by tiredofit** [comment]
There's a bit more than that required to make it happen but yes I could build that in.
What I'd need from you though is a one liner using psql to be able to check that a) the freescout database exists, and to see if the `users` table was empty. As that is part of my installation steps.

**Comment by hiaselhans** [comment]
thx @tiredofit 

i will be away until end of the week and start a pr then.
i remember a pitfall on the way but i think we can discuss it in a pr. :)
