### ISSUE TITLE
How to use db-backup?

### ISSUE THREAD

**Issue by svzi** [tiredofit/docker-freescout#38]
Hi @tiredofit ,

first of all thanks for the great repository! I'm running FreeScout now for several days without any issues so far. I really love it!

Can you please explain what is the environment variable  `DB_CLEANUP_TIME` meant for?

I would also like to know how use that backup in case of an emergency. I mean it's great to have a backup but it's not much worth if you don't know how to import it. Is there any documentation available?

Best,
Sven

**Comment by tiredofit** [comment]
Hi, check out the [tiredofit/db-backup](https://github.com/tiredofit/docker-db-backup) README for details on how to use that image.

**Comment by svzi** [comment]
Thanks a lot @tiredofit !
