### ISSUE TITLE
Unable to run on Raspberry Pi

### ISSUE THREAD

**Issue by bencgreen** [tiredofit/docker-freescout#41]
I was pleased to see that since 1.12.4 you have been compiling Docker images for ARM - however, they don't seem to work.

On my Raspberry Pi I'm getting this:

```
$ docker run tiredofit/freescout
standard_init_linux.go:219: exec user process caused: exec format error
```

The same thing happens when I specify a version - so far I've tried 1.12.7, 1.12.8, 1.12.9, 1.12.10, 1.12.11, 1.13.0, 1.13.1, 1.13.2 and 1.13.3.  After that I got bored and gave up!

This is normally caused by an architecture issue.  I'm afraid I have nothing more to go on than that - have you tested it on a Pi / other ARM platform?  Mine is a Raspberry Pi 4 so relatively new and certainly powerful enough to run Freescout (it already runs ownCloud and Bookstack).

Any assistance gratefully received.

**Comment by bencgreen** [comment]
Looking more closely at the Docker builds, the image sizes for different architectures seem suspiciously similar to me - I build my own images and the linux/amd64 image is usually different in size to the ARM images, by anything from 1-5%, yet the Freescout images on your account differ by about 10k.

I'm happy to help with an automated build process if you want?

**Comment by bencgreen** [comment]
So I've done more digging, trying to run the PHP images in the same way and found the same problem - until - this works:

```
$ docker run tiredofit/nginx
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
etc
```

But this doesn't:

```
$ docker run tiredofit/nginx:alpine-3.13
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error
```

A quick look on Docker Hub shows that the `alpine` tags on your `nginx` image are only built against `linux/amd64` - so even though subsequent images are built against different platforms, they are all actually using the `amd64` image, which explains why they are all the same size.

**Comment by tiredofit** [comment]
Ahh jeez, something has broken yes. Are my tiredofit/alpine images multiarch? Seems that some sort of github Actions could use a review, definitely feel free to check out my `workflows/main.yml` and we can make any potential changes.

**Comment by bencgreen** [comment]
Yes the `alpine` ones are fine - the issue seems to be with `nginx`, I'll have a look and see if I can figure out what's gone wrong.

**Comment by bencgreen** [comment]
I think it might be your latest builds of `nginx` don't seem to have the `alpine-` prefix any more, so I think in your PHP Dockerfiles if you just remove that and rebuild, it should all start working!

**Comment by tiredofit** [comment]
Ack - this is an oversight on my end. I need to add that prefix back. Let me look into this.

**Comment by tiredofit** [comment]
Have a pull on :latest if you could. Should be resolved?

**Comment by bencgreen** [comment]
All good!

```
$ docker run tiredofit/freescout:latest
Unable to find image 'tiredofit/freescout:latest' locally
latest: Pulling from tiredofit/freescout
069a56d6d07f: Pull complete
3b5c3f9aebd6: Pull complete
e859ad59662f: Pull complete
8bc5d3bbe9c0: Pull complete
2563fc3deb04: Pull complete
ed84c669345e: Pull complete
4fa19a0595a1: Pull complete
2c435f4d70a9: Pull complete
59dcc1ff7e1e: Pull complete
Digest: sha256:20e051543e6616cc323df2942fc03b5cafa69f98928a463464fac9af3ff1963e
Status: Downloaded newer image for tiredofit/freescout:latest
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
```

**Comment by bencgreen** [comment]
Thanks so much for such a speedy resolution, especially for something that I suspect wasn't a quick fix, even if it wasn't a hard one to track down.

**Comment by tiredofit** [comment]
You helepd with it So thanks! I haven't had much time to port things over to Github Actions (I find debugging when multiarch Docker builds fail to be very frustrating) so this gave me a bit of motivation. Glad it's working out.
