### ISSUE TITLE
1.14.3 tagged but not on docker hub

### ISSUE THREAD

**Issue by jugendhacker** [tiredofit/docker-freescout#46]
### Summary

Version 1.14.3 was tagged 17 days ago, but it wasn't uploaded to docker hub.

### Steps to reproduce

1. Look at tags
2. Find 1.14.3
3. Look at docker hub
4. Find 1.14.1 as latest tagged release

### What is the expected *correct* behavior?

Find the same release tagged in the git repo on docker hub.

### Possible fixes

Looks like you manually have to start the CI to upload a release, maybe run those task automatically every time a new tag gets pushed?

**Comment by tiredofit** [comment]
Github Actions fell over. I resubmitted, and the image is now avaialable..

**Comment by jugendhacker** [comment]
@tiredofit thanks
