### ISSUE TITLE
Issue with 1.15.1

### ISSUE THREAD

**Issue by skadefro** [tiredofit/docker-freescout#48]
### Summary

I run freescout on kubernetes, today i upgraded my cluster, so freescout and mariadb was restarted.
After it came up, i can login, I can see the different emails but if i click on any email i get "something went wrong" 
When setting version tag to 1.14.4 it all works again. but would be nice to be able to use latest

### Relevant logs and/or screenshots

In the console of mariadb there are no errors, but in freescout it says
```
PHP Startup: Unable to load dynamic library 'gnupg.so' (tried: /usr/lib/php8/modules/gnupg.so (Error loading shared library libgpgme.so.11: No such file or directory (needed by /usr/lib/php8/modules/gnupg.so)), /usr/lib/php8/modules/gnupg.so.so (Error loading shared library /usr/lib/php8/modules/gnupg.so.so: No such file or directory)) in Unknown on line 0
Cannot load Zend OPcache - it was already loaded
```
and
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'gnupg.so' (tried: /usr/lib/php8/modules/gnupg.so (Error loading shared library libgpgme.so.11: No such file or directory (needed by /usr/lib/php8/modules/gnupg.so)), /usr/lib/php8/modules/gnupg.so.so (Error loading shared library /usr/lib/php8/modules/gnupg.so.so: No such file or directory)) in Unknown on line 0
```
not sure if one of those is the reason, so I tried setting APP_DEBUG=true in hopes that would give me an error I could understand, but I just get presented with below, and it makes no sense to me
![image](https://user-images.githubusercontent.com/4155937/118605632-c57a7580-b7b6-11eb-876f-3a136da531ac.png)

- Image version / tag:  latest ( 1.15.1 at that time )

I originally made the [issue ](https://github.com/freescout-helpdesk/freescout/issues/1213) at freescout by mistake. But they where nice enough to tell, that there might be missing gnupg PHP extension ?

**Comment by XtomtomX** [comment]
Hi, i think this needs to be fixed on the php8 branch of "https://github.com/tiredofit/docker-nginx-php-fpm". I once posted an issue due to php 7.4 in the meantime freescout upgraded to php8. 

Link: https://github.com/tiredofit/docker-nginx-php-fpm/issues/16

**Comment by tiredofit** [comment]
@XtomtomX is correct - this was related to our upstream nginx-php-fpm image. I've resolved the problem and also issued a new Docker image of this project..

**Comment by skadefro** [comment]
Thank you for maintaining this, and thank you for fixing this issue fast :-)
