### ISSUE TITLE
SMTP Configuration issue

### ISSUE THREAD

**Issue by ChicagoGregg** [tiredofit/docker-freescout#49]
### Summary

I saw the other smtp issue in the Issues list in this repo, but that didn't help resolve.

The documentation references to have a clear understanding of the Alpine Linux image at URL: https://github.com/tiredofit/docker-alpine/#smtp-options

This URL also references at out-dated link -

Old link: http://msmtp.sourceforge.net/doc/msmtp.html
Correct link: https://marlam.de/msmtp/msmtp.html

I've spent a few hours trying to set various environment variables in attempts to get the Alpine Linux MSMTP to connect to my mail server (hosted on the same server as Docker), but it fails to send through.

### Steps to reproduce

1. Use no-proxy yaml file
2. Add any variety of the environment variables referenced to in the documentation (for Dockerfile)
3. Start up containers
4. Check /etc/msmtprc
5. The values never get changed
6. The postfix-relay host is unknown (Adding to the yaml file with extra_hosts does not help ths)

### What is the expected *correct* behavior?

Correct behavior is one of the following:

1. Send mail without any authentication (I configured the smtp server to accept from 172 addresses)
2. Send mail with LOGIN authentication and TLS (no check certificate)

### Environment

- Image version / tag:  Version 2 latest
- Host OS: Linux CentOS 7

<details>
<summary>docker-compose.yml</summary>
[gregg@xxxxxx docker-freescout]$ cat docker-compose.yml 
version: '2'

services:
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    ports:
    - 10080:80
    links:
    - freescout-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    # - /data/plabsorg/freescout-app/data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    - /data/xxxxxx/freescout-app/data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    #- ./modules:/www/html/Modules
    - /data/xxxxxx/freescout-app/logs:/www/logs

    environment:
    - ZABBIX_HOSTNAME=freescout-app
    
    - DB_HOST=freescout-db
    - DB_NAME=freescout
    - DB_USER=freescout
    - DB_PASS=freescout

    - SITE_URL=http://www.xxxxxx.org:10080
    - ADMIN_EMAIL=admin@domain.com
    - ADMIN_PASS=password
    - ENABLE_SSL_PROXY=FALSE
    - DISPLAY_ERRORS=TRUE
    - TIMEZONE=America/Los_Angeles
    restart: always
    extra_hosts:
      - "postfix-relay:172.17.0.1"

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - /data/xxxxxx/freescout-db/db:/var/lib/mysql
    environment:
      - ROOT_PASS=password
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout

      - ZABBIX_HOSTNAME=freescout-db
    restart: always
    extra_hosts:
      - "smtp-relay:127.0.0.1"

  freescout-db-backup:
    container_name: freescout-db-backup
    image: tiredofit/db-backup
    links:
     - freescout-db
    volumes:
      - /data/xxxxxx/freescout-db-backup/dbbackup:/backup
    environment:
      - ZABBIX_HOSTNAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    restart: always
    extra_hosts:
      - "smtp-relay:127.0.0.1"
</details>

![freescout screenshot 2021-05-22_02-05-17](https://user-images.githubusercontent.com/2259414/119221059-5c3e7f00-baa2-11eb-9655-123dc19cf89e.jpg)
    
### Possible fixes

Trying from a docker exec session using sendmail still not working... Still troubleshooting...

**Comment by tiredofit** [comment]
I never did like the PHP sending capability in Freescout. MSMTP is finnicky as well - I use this in production: https://github.com/tiredofit/docker-postfix-relay to send out SMTP to an external server. 

Not sure why your msmtprc settings aren't being changed, I can't recreate on my end. Will update readme though, thanks.

**Comment by ChicagoGregg** [comment]
On a brand new Ubuntu install with docker, I just tried and the variables aren't affecting the /etc/msmtprc configuration as well.

One thing I noticed in the 'docker-compose up' is that the variables aren't listed, but that's probably fine since it's the first startup and creating the .env file.

Just so we're on the same page, the Dockerfile is where I'm setting the ENABLE_SMTP=TRUE and SMTP_* variables. It's like it's completely ignoring it.

So if I go the route of installing a docker-postfix-relay container, and link it [in the yam file], I wonder if that's really just unnecessary since the docker is on the same host as the mail server. :) But I suppose it would give more flexibility if I did it that way, too.

Here's some startup messages to see if anything out of the ordinary can be seen:

`mylogin@gmlaptop:~/work/git/freescout/docker-freescout$ docker-compose up
Creating network "docker-freescout_default" with the default driver
Pulling freescout-db (tiredofit/mariadb:)...
latest: Pulling from tiredofit/mariadb
fa7045767063: Pull complete
50f1515ac8b1: Pull complete
8754f8456914: Pull complete
d23ff9e84792: Pull complete
3b38e30a73be: Pull complete
Digest: sha256:b7ca4caccf387b9f622637dbdf11efb9f4ecc0f569ce1e80b4adb15b0760954b
Status: Downloaded newer image for tiredofit/mariadb:latest
Pulling freescout-app (tiredofit/freescout:)...
latest: Pulling from tiredofit/freescout
540db60ca938: Pull complete
3c0771138687: Pull complete
2ab2e01f37c1: Pull complete
132b87958b52: Pull complete
0ba03b64fe98: Pull complete
672fc0a4ed86: Pull complete
2e02b51bfad0: Pull complete
acab62c4f9e6: Pull complete
ff04efdf717e: Pull complete
Digest: sha256:112d185a282b219c96cd037267cffd678d5ab6bc65ccda919c425304e847a4f0
Status: Downloaded newer image for tiredofit/freescout:latest
Pulling freescout-db-backup (tiredofit/db-backup:)...
latest: Pulling from tiredofit/db-backup
540db60ca938: Already exists
e39bf16ed0f4: Pull complete
40f7a01cd3bd: Pull complete
c8389f873979: Pull complete
1f49724042f8: Pull complete
Digest: sha256:bccf7baa41e082437105b9b8b5cb8f19a492dc9295a15f886421e3f545285640
Status: Downloaded newer image for tiredofit/db-backup:latest
Creating freescout-db ... done
Creating freescout-app       ... done
Creating freescout-db-backup ... done
Attaching to freescout-db, freescout-db-backup, freescout-app
freescout-db           | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
freescout-db           | [s6-init] ensuring user provided files have correct perms...exited 0.
freescout-db           | [fix-attrs.d] applying ownership & permissions fixes...
freescout-db           | [fix-attrs.d] 00-functions: applying... 
freescout-db           | [fix-attrs.d] 00-functions: exited 0.
freescout-db           | [fix-attrs.d] 01-s6: applying... 
freescout-db           | [fix-attrs.d] 01-s6: exited 0.
freescout-db           | [fix-attrs.d] 02-zabbix: applying... 
freescout-db           | [fix-attrs.d] 02-zabbix: exited 0.
freescout-db           | [fix-attrs.d] 03-logrotate: applying... 
freescout-db           | [fix-attrs.d] 03-logrotate: exited 0.
freescout-db           | [fix-attrs.d] done.
freescout-db           | [cont-init.d] executing container initialization scripts...
freescout-db           | [cont-init.d] 00-startup: executing... 
freescout-db           | [cont-init.d] 00-startup: exited 0.
freescout-db           | [cont-init.d] 01-timezone: executing... 
freescout-db           | [cont-init.d] 01-timezone: exited 0.
freescout-db           | [cont-init.d] 02-permissions: executing... 
freescout-db           | [cont-init.d] 02-permissions: exited 0.
freescout-db           | [cont-init.d] 03-zabbix: executing... 
freescout-db           | [cont-init.d] 03-zabbix: exited 0.
freescout-db           | [cont-init.d] 04-cron: executing... 
freescout-db           | [NOTICE] ** [cron] Disabling Cron
freescout-db           | [cont-init.d] 04-cron: exited 0.
freescout-db           | [cont-init.d] 05-smtp: executing... 
freescout-db           | [NOTICE] ** [smtp] Disabling SMTP Features
freescout-db           | [cont-init.d] 05-smtp: exited 0.
freescout-db           | [cont-init.d] 10-mariadb: executing... 
freescout-db           | [WARN] ** [mariadb] MariaDB data directory is not found, creating initial DB(s)
freescout-db-backup    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
freescout-app          | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
freescout-db-backup    | [s6-init] ensuring user provided files have correct perms...exited 0.
freescout-db-backup    | [fix-attrs.d] applying ownership & permissions fixes...
freescout-db-backup    | [fix-attrs.d] 00-functions: applying... 
freescout-app          | [s6-init] ensuring user provided files have correct perms...exited 0.
freescout-app          | [fix-attrs.d] applying ownership & permissions fixes...
freescout-app          | [fix-attrs.d] 00-functions: applying... 
freescout-db-backup    | [fix-attrs.d] 00-functions: exited 0.
freescout-db-backup    | [fix-attrs.d] 01-s6: applying... 
freescout-app          | [fix-attrs.d] 00-functions: exited 0.
freescout-app          | [fix-attrs.d] 01-s6: applying... 
freescout-db-backup    | [fix-attrs.d] 01-s6: exited 0.
freescout-db-backup    | [fix-attrs.d] 02-zabbix: applying... 
freescout-app          | [fix-attrs.d] 01-s6: exited 0.
freescout-app          | [fix-attrs.d] 02-zabbix: applying... 
freescout-db-backup    | [fix-attrs.d] 02-zabbix: exited 0.
freescout-db-backup    | [fix-attrs.d] 03-logrotate: applying... 
freescout-db-backup    | [fix-attrs.d] 03-logrotate: exited 0.
freescout-db-backup    | [fix-attrs.d] done.
freescout-db-backup    | [cont-init.d] executing container initialization scripts...
freescout-db-backup    | [cont-init.d] 00-startup: executing... 
freescout-db-backup    | [cont-init.d] 00-startup: exited 0.
freescout-db-backup    | [cont-init.d] 01-timezone: executing... 
freescout-app          | [fix-attrs.d] 02-zabbix: exited 0.
freescout-app          | [fix-attrs.d] 03-logrotate: applying... 
freescout-db-backup    | [cont-init.d] 01-timezone: exited 0.
freescout-db-backup    | [cont-init.d] 02-permissions: executing... 
freescout-app          | [fix-attrs.d] 03-logrotate: exited 0.
freescout-app          | [fix-attrs.d] done.
freescout-app          | [cont-init.d] executing container initialization scripts...
freescout-app          | [cont-init.d] 00-startup: executing... 
freescout-db-backup    | [cont-init.d] 02-permissions: exited 0.
freescout-db-backup    | [cont-init.d] 03-zabbix: executing... 
freescout-app          | [cont-init.d] 00-startup: exited 0.
freescout-app          | [cont-init.d] 01-timezone: executing... 
freescout-app          | [NOTICE] ** [timezone] Timezone: Setting to 'America/Los_Angeles' from 'Etc/GMT'
freescout-app          | [cont-init.d] 01-timezone: exited 0.
freescout-app          | [cont-init.d] 02-permissions: executing... 
freescout-db-backup    | [cont-init.d] 03-zabbix: exited 0.
freescout-db-backup    | [cont-init.d] 04-cron: executing... 
freescout-app          | [cont-init.d] 02-permissions: exited 0.
freescout-app          | [cont-init.d] 03-zabbix: executing... 
freescout-db-backup    | [NOTICE] ** [cron] Disabling Cron
freescout-db-backup    | [cont-init.d] 04-cron: exited 0.
freescout-db-backup    | [cont-init.d] 05-smtp: executing... 
freescout-db-backup    | [NOTICE] ** [smtp] Disabling SMTP Features
freescout-app          | [cont-init.d] 03-zabbix: exited 0.
freescout-app          | [cont-init.d] 04-cron: executing... 
freescout-db-backup    | [cont-init.d] 05-smtp: exited 0.
freescout-db-backup    | [cont-init.d] 99-container: executing... 
freescout-app          | [cont-init.d] 04-cron: exited 0.
freescout-app          | [cont-init.d] 05-smtp: executing... 
freescout-app          | [NOTICE] ** [smtp] Sendmail replaced and enabled to route mail to: 'postfix-relay'
freescout-app          | [cont-init.d] 05-smtp: exited 0.
freescout-db-backup    | [cont-init.d] 99-container: exited 0.
freescout-app          | [cont-init.d] 10-nginx: executing... 
freescout-db-backup    | [cont-init.d] done.
freescout-db-backup    | [services.d] starting services
freescout-db-backup    | [services.d] done.
freescout-db-backup    | [INFO] ** [zabbix] Starting Zabbix Agent
freescout-db           | [NOTICE] ** [mariadb] Creating freescout database
freescout-db           | 2021-05-23  1:46:22 0 [Note] /usr/bin/mysqld (mysqld 10.5.10-MariaDB) starting as process 802 ...
freescout-db           | 2021-05-23  1:46:22 0 [Note] InnoDB: Uses event mutexes
freescout-db           | 2021-05-23  1:46:22 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
freescout-db           | 2021-05-23  1:46:22 0 [Note] InnoDB: Number of pools: 1
freescout-db           | 2021-05-23  1:46:22 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
freescout-db           | 2021-05-23  1:46:22 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
freescout-app          | [NOTICE] ** [nginx] Disable Nginx FastCGI HTTPS Termination Support
freescout-app          | [cont-init.d] 10-nginx: exited 0.
freescout-app          | [cont-init.d] 11-nginx-config-reload: executing... 
freescout-db           | 2021-05-23  1:46:22 0 [Note] InnoDB: Using Linux native AIO
freescout-app          | [cont-init.d] 11-nginx-config-reload: exited 0.
freescout-db           | 2021-05-23  1:46:22 0 [Note] InnoDB: Initializing buffer pool, total size = 268435456, chunk size = 134217728
freescout-app          | [cont-init.d] 20-php-fpm: executing... 
freescout-db           | 2021-05-23  1:46:22 0 [Note] InnoDB: Completed initialization of buffer pool
freescout-db           | 2021-05-23  1:46:22 0 [Note] InnoDB: 128 rollback segments are active.
freescout-db           | 2021-05-23  1:46:22 0 [Note] InnoDB: Creating shared tablespace for temporary tables
freescout-db           | 2021-05-23  1:46:22 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
freescout-db           | 2021-05-23  1:46:22 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
freescout-db           | 2021-05-23  1:46:22 0 [Note] InnoDB: 10.5.10 started; log sequence number 45130; transaction id 20
freescout-db           | 2021-05-23  1:46:22 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
freescout-db           | 2021-05-23  1:46:22 0 [Note] InnoDB: Buffer pool(s) load completed at 210523  1:46:22
freescout-db           | 2021-05-23  1:46:22 1 [Warning] 'user' entry 'root@c23cf810667e' ignored in --skip-name-resolve mode.
freescout-db           | 2021-05-23  1:46:22 1 [Warning] 'user' entry '@c23cf810667e' ignored in --skip-name-resolve mode.
freescout-db           | 2021-05-23  1:46:22 1 [Warning] 'proxies_priv' entry '@% root@c23cf810667e' ignored in --skip-name-resolve mode.
freescout-db           | 2021-05-23  1:46:22 1 [Warning] 'user' entry 'root@c23cf810667e' ignored in --skip-name-resolve mode.
freescout-db           | 2021-05-23  1:46:22 1 [Warning] 'user' entry '@c23cf810667e' ignored in --skip-name-resolve mode.
freescout-db           | 2021-05-23  1:46:22 1 [Warning] 'proxies_priv' entry '@% root@c23cf810667e' ignored in --skip-name-resolve mode.
freescout-db           | [cont-init.d] 10-mariadb: exited 0.
freescout-db           | [cont-init.d] 20-mariadb-backup: executing... 
freescout-db           | [NOTICE] ** [mariadb-backup] Disabling scheduled backups
freescout-db           | [cont-init.d] 20-mariadb-backup: exited 0.
freescout-db           | [cont-init.d] 99-container: executing... 
freescout-db           | [cont-init.d] 99-container: exited 0.
freescout-db           | [cont-init.d] done.
freescout-db           | [services.d] starting services
freescout-db           | [services.d] done.
freescout-db           | [INFO] ** [mariadb] Starting MariaDB 10.5.10
freescout-db           | [INFO] ** [zabbix] Starting Zabbix Agent 5.2.5
freescout-app          | [NOTICE] ** [php-fpm] PHP-FPM Preparing to start with the following plugins enabled:  apcu bcmath bz2 ctype curl dom exif fileinfo gd gnupg iconv imap intl ldap mbstring mysqli mysqlnd opcache openssl pdo pdo_mysql pgsql phar session simplexml tokenizer xml xmlreader xmlwriter zip
freescout-app          | [cont-init.d] 20-php-fpm: exited 0.
freescout-app          | [cont-init.d] 30-freescout: executing... 
freescout-app          | [WARN] ** [freescout] Potential New Installation / Standalone Installation Detected - Copying Freescout Sourcecode
freescout-app          | [WARN] ** [freescout] Detected /data directory. Persistently saving settings/sessions/cache/uploads/modules
freescout-app          | [INFO] ** [freescout] Generating Configuration
freescout-app          | #### Automatically Generated File - Upon container restart any settings will reset!
freescout-app          | APP_URL=http://gglaptop:10080
freescout-app          | APP_FORCE_HTTPS=false
freescout-app          | APP_DEBUG=true
freescout-app          | APP_KEY=
freescout-app          | DB_CONNECTION=mysql
freescout-app          | DB_HOST=freescout-db
freescout-app          | DB_PORT=3306
freescout-app          | DB_DATABASE=freescout
freescout-app          | DB_USERNAME=freescout
freescout-app          | DB_PASSWORD=freescout
freescout-app          | APP_DISABLE_UPDATING=true
freescout-app          | [WARN] ** [freescout] Detected empty Database - Setting up - Please wait..
freescout-app          | [WARN] ** [freescout] Creating Administrative User
freescout-app          | User created with id: 1
freescout-app          | [WARN] ** [freescout] Installing Modules into container
freescout-app          | [WARN] ** [freescout] Running any Database Migrations
freescout-db-backup    | [NOTICE] ** [db-backup] Next Backup at 2021-05-24 00:00:00 GMT
freescout-app          | [INFO] ** [freescout] Initialization Complete. Please visit http://gglaptop:10080 and login with your credentials..
freescout-app          | [cont-init.d] 30-freescout: exited 0.
freescout-app          | [cont-init.d] 99-container: executing... 
freescout-app          | [cont-init.d] 99-container: exited 0.
freescout-app          | [cont-init.d] done.
freescout-app          | [services.d] starting services
freescout-app          | [services.d] done.
freescout-app          | [INFO] ** [nginx] Starting nginx 1.20.0
freescout-app          | [INFO] ** [zabbix] Starting Zabbix Agent 5.4.0
freescout-app          | [INFO] ** [php-fpm] Starting php-fpm 8.0.6
freescout-app          | [INFO] ** [cron] Starting cron`

**Comment by ChicagoGregg** [comment]
So, my mistake I put the variables in the Dockerfile instead of the yaml file. Now that I have those in the yaml file, the emails go out without any errors ONLY when I go through the shell and execute sendmail.

They still error out through the FS PHP route.

How can I tell the PHP Mail to use sendmail? I've tried MAIL_DRIVER=sendmail (Laravel), through the config/.env, and messing around with some others. I wish I could find out how to debug the PHP Mail sending more in-depth but I can't find any articles on this; nor are the APP_DEBUG=true and APP_LOG_LEVEL=error helpful.

Thanks!!!

-gregg

**Comment by tiredofit** [comment]
It's automatic if you ENABLE_SMTP set in your docker-compose...

See what happens when the container initializes..

https://github.com/tiredofit/docker-nginx-php-fpm/blob/fc2b64a0075a6213a2dfb345f539d3bc18677af0/install/etc/cont-init.d/20-php-fpm#L134

**Comment by ChicagoGregg** [comment]
I found out the issue.

The /etc/msmtprc file needs to be owned by nginx with 600 permissions. The emails are sending out properly now.

Now I just need to figure out why emails aren't being received at one of my email addresses, but that's another issue aside from this. :)

**Comment by tiredofit** [comment]
Interesting - I'm aware of a .msmtprc in a users home directory with those permissions but not the system wide configuraiton. Will have to review and see if I can recreate this. 

Email can be tricky, I have guys who are regularly pulling out there hair trying to deliver to certain hosts. DKIM, DMARC, SPF is just a confusing mess at this stage.

**Comment by tiredofit** [comment]
I was able to confirm your findings via the Arch Linux wiki - I've updated the upstream PHP-FPM image permission for `/etc/msmtprc` as `nginx:www-data`, the `:latest` image should have the changes reflected in it, otherwise for sure in the next tagged release.

**Comment by ChicagoGregg** [comment]
I was able to check this out really quick. Looks like the "chmod 600" is incorrect. :)

`[gregg@sirius docker-freescout]$ docker exec -ti freescout-app bash
bash-5.1# ls -ld /etc/ms*
-rw-r--r--    1 600      root           282 May 29 02:35 /etc/msmtprc
`

**Comment by tiredofit** [comment]
Oh how embarrassing.  I'm moving too fast juggling other things so I apologize. Have fixed this upstream and will make new images to fix that.

**Comment by ChicagoGregg** [comment]
It happens to all of us! Many thanks!

I confirmed this is working. We'll close this issue.
