### ISSUE TITLE
Error in building the container

### ISSUE THREAD

**Issue by openemail** [tiredofit/docker-freescout#5]
+ apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing gnu-libiconv
fetch http://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  gnu-libiconv (missing):
    required by: world[gnu-libiconv]
The command '/bin/sh -c set -x &&       apk update &&   apk upgrade &&          apk add         expect         nginx         mariadb-client         openssl         php7-apcu         php7-bz2         php7-cli         php7-ctype         php7-curl         php7-dom         php7-embed         php7-fileinfo         php7-fpm         php7-gd         php7-iconv         php7-imap         php7-json         php7-mbstring         php7-mysqli         php7-opcache         php7-openssl         php7-pdo         php7-pdo_mysql         php7-phar         php7-session         php7-simplexml         php7-tokenizer         php7-xml         php7-xmlrpc         php7-zip         php7-zlib         &&         apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing         gnu-libiconv         &&         sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g' /etc/php7/php.ini &&     ln -s /sbin/php-fpm7 /sbin/php-fpm &&         curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer &&         mkdir -p /www/logs &&     mkdir -p /www/html &&     curl -sSL https://github.com/freescout-helpdesk/freescout/archive/${FREESCOUT_VERSION}.tar.gz | tar xvfz - --strip 1 -C /www/html &&     chown -R nginx:www-data /www/html &&         rm -rf /usr/src/* /var/tmp/* /var/cache/apk/*' returned a non-zero code: 1

**Comment by tiredofit** [comment]
Looks like they've moved libiconv out of testing and into community for next release - I'm going to fix this and send a new build up to Docker Hub immediately.

**Comment by tiredofit** [comment]
New build is live

**Comment by openemail** [comment]
Thank you, the great !!!
