### ISSUE TITLE
[freescout] MySQL/MariaDB Server 'freescout-db' is not accessible, retrying..

### ISSUE THREAD

**Issue by couquino** [tiredofit/docker-freescout#52]
### Summary

We're currently trying to install Freescout on a test server before putting it in production, and we have the following error : 
`[freescout] MySQL/MariaDB Server 'freescout-db' is not accessible, retrying..`
The database is running fine

### Steps to reproduce

- Deploy using the docker-compose.yml
- Start the stack

### What is the expected *correct* behavior?

The DB should be found

### Relevant logs and/or screenshots

`[freescout] MySQL/MariaDB Server 'freescout-db' is not accessible, retrying..`

docker-compose.yml
`version: '3.3'
services:
  freescout-app:
    image: tiredofit/freescout:latest
    labels:
      traefik.http.routers.freescout.middlewares: freescout-https-redirect
      traefik.http.routers.freescout.rule: Host(`******`)
      traefik.http.services.freescout.loadbalancer.server.port: '80'
      traefik.http.middlewares.freescout-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.freescouts.entrypoints: https
      traefik.http.routers.freescout.entrypoints: http
      traefik.http.routers.freescouts.service: freescout-app
      traefik.http.routers.freescouts.tls.certresolver: http
      traefik.http.routers.freescouts.rule: Host(`******`)
      traefik.http.routers.freescouts.tls: 'true'
      traefik.docker.network: traefik_default
      traefik.enable: 'true'
    environment:
      ADMIN_EMAIL: ******
      ADMIN_PASS: ******
      DB_HOST: freescout-db
      DB_NAME: freescout
      DB_PASS: ******
      DB_PORT: '33062'
      DB_USER: ******
      DISPLAY_ERRORS: 'FALSE'
      ENABLE_SSL_PROXY: 'FALSE'
      SITE_URL: ******
      TIMEZONE: Europe/Paris
    ports:
     - 30129:80
    volumes:
     - /home/******/freescout/data:/data
     - /home/******/freescout/logs:/www/logs
    networks:
     - freescout
     - traefik_default
    logging:
      driver: json-file
  freescout-db:
    image: tiredofit/mariadb:latest
    environment:
      DB_NAME: freescout
      DB_PASS: ******
      DB_USER: ******
      ROOT_PASS: ******
    ports:
     - 33062:3306
    volumes:
     - /home/******/freescout/db:/var/lib/mysql
    networks:
     - freescout
    logging:
      driver: json-file
  freescout-db-backup:
    image: tiredofit/db-backup:latest
    environment:
      COMPRESSION: BZ
      DB_CLEANUP_TIME: '8640'
      DB_DUMP_BEGIN: '0000'
      DB_DUMP_FREQ: '1440'
      DB_HOST: freescout-db
      DB_NAME: ******
      DB_PASS: ******
      DB_TYPE: mariadb
      DB_USER: ******
      MD5: 'TRUE'
    networks:
     - freescout
    logging:
      driver: json-file
networks:
  freescout:
    driver: overlay
  traefik_default:
    external: true
`

### Environment

- Image version / tag: latest
- Host OS: Ubuntu 18.04.5 LTS 

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>

**Comment by jonathan-brown** [comment]
I am also getting this error, trying to install on AWS lightsail containers.... I have used the following 

[44m[WARN][49m ** [freescout] MySQL/MariaDB Server 'freescout-db' is not accessible, retrying.. (5 seconds so far)


image - tiredofit/freescout:latest

DB_HOST - freescout-db
DB_USER - freescout
DB_NAME - freescout
DB_PASS - password
DB_PORT - 3306
DISPLAY_ERRORS - TRUE
SITE_URL - my-site-name

**Comment by couquino** [comment]
We tried a MariaDB 5.6 image and it worked perfectly.

Maybe it’s a solution


Le 3 juil. 2021 à 09:04, Jonathan Brown ***@***.***> a écrit :

﻿

I am also getting this error, trying to install on AWS lightsail containers.... I have used the following

�[44m[WARN]�[49m ** [freescout] MySQL/MariaDB Server 'freescout-db' is not accessible, retrying.. (5 seconds so far)

image - tiredofit/freescout:latest

DB_HOST - freescout-db
DB_USER - freescout
DB_NAME - freescout
DB_PASS - password
DB_PORT - 3306
DISPLAY_ERRORS - TRUE
SITE_URL - my-site-name

**Comment by jonathan-brown** [comment]
Does the free scout image not have a db image set up though ?

**Comment by tiredofit** [comment]
Image doesn't have a DB in it, but libraries to connect to seperate DB containers - 

Head inside the container and execute this and see if it throws any errors - this is the check I am doing to see if your DB Host is available:

`mysql -u"${DB_USER}" -P"${DB_PORT}" -h"${DB_HOST}" -p"${DB_PASS}" -e "SELECT COUNT(*) FROM information_schema.FILES;" 2>&1 | grep -E "COUNT|Enter"`

**Comment by jonathan-brown** [comment]
<img width="610" alt="Screenshot 2021-07-04 at 18 45 55" src="https://user-images.githubusercontent.com/12933140/124394650-44405900-dcf8-11eb-9b54-2c1651e437c6.png">


Still getting same error when i have the standalone db container

**Comment by tiredofit** [comment]
See my above content, everything you have posted looks right, but I can't tell if we've got connectivity to each other.

You can also try pinging the mariadb container from the freescout container to make sure they can at least see each other.

**Comment by jonathan-brown** [comment]
yeah thats seems to be the issue, the containers cant see each other. Strange as they are both running within the same master lightsail container service. 

 Thanks for your help anyway

**Comment by wzulfikar** [comment]
Just had this issue and the error wasn't connectivity error, rather than because i was using mysql 8 for db. The actual error is "Plugin caching_sha2_password could not be loaded: Error loading shared library /usr/lib/mariadb/plugin/caching_sha2_password.so" but it was buried under "[freescout] MySQL/MariaDB Server 'freescout-db' is not accessible, retrying.". 

Once I fixed that mysql error (by changing the login to native password), I can connect to my db.

**Comment by wzulfikar** [comment]
For me, running this sql fixed my issue:
```
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'somepassword'
```

Basically, mysql 8 uses new type of auth that's not supported by mysql 5. Above query updates my user to use the auth method that's backward compatible. I guess, ideally, we should update the PHP code to support the new auth method. But this approach is just fine for me.

Here's the [SO](https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded) thread for context.

**Comment by tiredofit** [comment]
Just tagged `tiredofit/freescout:1.7.19` which will be available on Docker Hub momentarily which has updated base image changes to support the SHA2 plugin.. Let me know..

**Comment by geoffjukes** [comment]
Hi,

I was attempting to use an existing Percona 5.7 DB instance, with a dedicated user (i.e. not root) and kept hitting this issue. This reply revealed the user I was using didn't have the `PROCESS` privilege.

> Image doesn't have a DB in it, but libraries to connect to seperate DB containers -
> 
> Head inside the container and execute this and see if it throws any errors - this is the check I am doing to see if your DB Host is available:
> 
> `mysql -u"${DB_USER}" -P"${DB_PORT}" -h"${DB_HOST}" -p"${DB_PASS}" -e "SELECT COUNT(*) FROM information_schema.FILES;" 2>&1 | grep -E "COUNT|Enter"`

I'm not super comfortable with giving this app any Administrative privileges. Is this a requirement? or can I safely remove it after the DB has built?

**Comment by tiredofit** [comment]
What that is is a check to see if a) the DB can be connected to not only by port, but that the client can execute commands.
If you can come up with a command that works in a similar fashion I will work it into the base images.

https://github.com/tiredofit/docker-db-backup/issues/72 has a lengthy discussion about it as well, very similar. I haven't acted due to time/motivation/lack of using MySQL (only MariaDB).

**Comment by geoffjukes** [comment]
I was going to suggest using `show grants` and I can see same was suggested in https://github.com/tiredofit/docker-db-backup/issues/72#issuecomment-991960936
I'm using Percona, and it works. I think this should suffice:

```
mysql -u"${DB_USER}" -P"${DB_PORT}" -h"${DB_HOST}" -p"${DB_PASS}" -e "SHOW GRANTS FOR CURRENT_USER;" 2>&1 | grep -E "GRANT ALL PRIVILEGES ON `${DB_NAME}`"
```

I don't think it unreasonable to assume the FreeScout user has "all" rights to its own schema.

**Comment by tiredofit** [comment]
Agreed on the schema permissions. That's generally how the official mariadb image works (and my own tiredofit/mariadb) that the user defined gets full access to the db in question. 

I'll look at this tomorrow afternoon by skimming through all my code as I have a feeling this DB check is all the way up in the highest of my base images which means we have a day "ish" to rebuild them all before it makes it to the Freescout image. Bonus though it will solve this from happening in any of the other 60+ I maintain. Will update when I know more,

**Comment by tiredofit** [comment]
OK! Have a peek at `tiredofit/freescout:1.15.26` as an image. This theoretically _should_ get MySQL and Percona past the initial DB connectivity check based on your work. and oneliner.

**Comment by geoffjukes** [comment]
@tiredofit Worked perfectly for me, thanks!

**Comment by tiredofit** [comment]
Thank you very much for contributing to the solution of this long standing problem!

I will close.

**Comment by tiredofit** [comment]
FWIW I applied the same fix to db-backup too !

**Comment by geoffjukes** [comment]
That's great. Glad I could help :)

**Comment by tiredofit** [comment]
@geoffjukes It looks as if there is an unintended effect of the change that has limited the ability for people using "root" to select grants which has only recently shown itself [here](https://github.com/tiredofit/docker-db-backup/issues/94). I was wondering if you have any advice or input on how I would be able to get people back up and running for these scenarios?

**Comment by geoffjukes** [comment]
@tiredofit A quick fix would be to change:

```"GRANT ALL PRIVILEGES ON `${DB_NAME}`"```
to 
```"GRANT ALL PRIVILEGES ON \*|`${DB_NAME}`"```

which should cover the "user who has all privileges to all schemas"

For users that specify specific privileges, you could simply note that the "FreeScout Database user requires 'ALL'". Certainly the old requirement for the administrative `PROCESS` privilege was not noted anywhere.

The only way to fully satisfy all possible variations of the user privileges', would be to create a test table, add a row to it, and remove the row. That would be three steps, but something like:

```
"CREATE TABLE IF NOT EXISTS \`${DB_NAME}\`.\`startup\` (  \`timestamp\` datetime, PRIMARY KEY (\`timestamp\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;"

"INSERT INTO \`${DB_NAME}\`.\`startup\` (\`timestamp\`) VALUES (NOW());"

"DROP TABLE \`${DB_NAME}\`.\`startup\`;"
```
in three separate calls. Each should complete with no data, and the last return executions value (`echo $?`) should be 0.

Alternatively, you could simply remove the check altogether, and catch DB errors if/when they happen. Doing it that way would catch issues with permissions resulting from changes made after the app is started.

**Comment by tiredofit** [comment]
I agree, a simple connect (something more than a nc) would be useful, like a `mysqladmin` something or other test. Off the top of your head, do you know a great one liner I can integrate? I'm sorry to be siphoning great ideas from you, I am in the busiest time of the last decade it seems and don't have many cycles to think creatively at this time other than just "keep the lights on". Things have become magnified lately when I've found my public repos are actually being used by people :)

**Comment by geoffjukes** [comment]
No worries @tiredofit, glad to help.

Quick and dirty, change the grep to just "GRANT". A successful connection should always return one or more rows. 

Geoff
