### ISSUE TITLE
Syntax error in 30-freescout

### ISSUE THREAD

**Issue by bfren** [tiredofit/docker-freescout#54]
### Steps to reproduce

* Updated to 1.15.8
* Restarted container

### What is the expected *correct* behavior?

* Container should start

### Relevant logs and/or screenshots

The following is in docker logs:

```shell
/var/run/s6/etc/cont-init.d/30-freescout: line 269: syntax error near unexpected token `fi'
/var/run/s6/etc/cont-init.d/30-freescout: line 269: `fi'
```

### Environment

- Image version / tag:  1.15.8
- Host OS: Ubuntu 20

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>

    
### Possible fixes

Possibly the `fi` is left from a previous conditional?

**Comment by tiredofit** [comment]
Oh jeez, I am terribly sorry about this. 
Fixed in `https://github.com/tiredofit/docker-freescout/commit/b7a3f16988cce18c9de3fd990325dbd8875ca381` which is also tagged as `1.15.9` and should be on Docker Hub shortly.
