### ISSUE TITLE
Empty DB after update

### ISSUE THREAD

**Issue by afawaz2** [tiredofit/docker-freescout#55]
### Summary

I pulled the latest mariadb and freescout images. The result ended up with mariadb showing empty. I persist mariadb to db volume.

**Comment by afawaz2** [comment]
I jumped from version 1.7.10 to 1.7.13

**Comment by bfren** [comment]
This was mentioned in #53 and #54 - there was supposed to be a fix in the latest version, but the same thing happened again, not sure what the issue is with the initialisation script.

**Comment by tiredofit** [comment]
This is now resolved with the :`latest` or :`1.15.10` - My apologies, a file was removed from one of the past few commits which broke the initialization routines.

**Comment by afawaz2** [comment]
It works now. Thank you.
