### ISSUE TITLE
Pulling installs PHP 8

### ISSUE THREAD

**Issue by cmer** [tiredofit/docker-freescout#56]
I pulled the latest update, which seems to install PHP 8 and break FreeScout. Dependencies require PHP 7.

**Comment by cmer** [comment]
<img width="1413" alt="CleanShot 2021-09-26 at 10 33 07@2x" src="https://user-images.githubusercontent.com/412/134812244-b35d3131-2830-43b5-b1e6-de2c21bc592f.png">

**Comment by tiredofit** [comment]
We've been on PHP 8 for a few months now. What are you trying to do inside the image to get this to show up? Have a peek at the Dockerfile and see the flags I pass to get composer to operate.

**Comment by cmer** [comment]
Ok I figured it out. I upgraded to 1.13.3 first, then to `latest`. I still had issues and had to do:

`chown -R nginx:www-data /data`

Now all is good!
