### ISSUE TITLE
Docker image without zabbix agent - port is already in use

### ISSUE THREAD

**Issue by tuxmartin** [tiredofit/docker-freescout#67]
Hi, I have zabbix agent on my server. 

If I start your docker container with `network_mode: host`, my zabbix agent on server cannot start. Port is already in use.

Is possible to disable zabbix agent in docker image? Something like env variable will be great.

Thanks.

**Comment by tiredofit** [comment]
Have a peek at this in the documentation specifically the base images used: https://github.com/tiredofit/docker-freescout#environment-variables

**Comment by tuxmartin** [comment]
@tiredofit thank you. I found `CONTAINER_ENABLE_MONITORING=FALSE`.
