### ISSUE TITLE
I got something to work.. but not enough to keep the container.. 

### ISSUE THREAD

**Issue by bcookatpcsd** [tiredofit/docker-freescout#68]
I have a localized install and wanted to put the app into docker.. 

importing the DB was a little confusing.. 

All of the content in our other setup, was also difficult.. 

But I could not figure out the ssl frontend.. 

I had to put it on hold for the time being as the hours to migrate it to another localized install will work in the end.. 

What is the trick to have a working https://freescout-or-whatever.domain.name setup? 

Thanks in advance.. 

If it helps.. 

Here is a working Caddyfile for freescout

Possibly it might be easier to put freescout inside caddy and then docker that.. 

`

{
        acme_ca https://acme.zerossl.com/v2/DV90
        email name+ssl@domain.org
        servers :443 {
                protocol {
                        experimental_http3
                }
        }
}

{
}

(stdcfg) {
        encode {
                zstd
                gzip 1
        }

        push

        header {
                -server
                Strict-Transport-Security max-age=31536000;
                X-Content-Type-Options nosniff;
                X-XSS-Protectoin "1; mode=block;"
                X-Robots-Tag none;
                X-Frame-Options SAMEORIGIN;
                Referrer-Policy no-referrer;
        }
}

https://freescout.support.domain.org {
        root * /srv/http/freescout/public

        file_server

        php_fastcgi unix//run/php-fpm7/php-fpm.sock

        tls name+freescout@domain.org {
                 protocols tls1.2 tls1.3
        }

        import stdcfg

log {
        output stdout
        format single_field common_log
}

}
`

**Comment by tiredofit** [comment]
This isn't related to the image, but more so your reverse proxy setup. Closing the issue. Perhaps you can move this to 'Discussions' to see if anyone is able to help.
