### ISSUE TITLE
1.15.51 docker image doesn't seem to work

### ISSUE THREAD

**Issue by ybizeul** [tiredofit/docker-freescout#83]
### Summary

Running 1.15.51 image, it seems nginx isn't started

### Steps to reproduce

Running in kubernetes the `latest` version and suddenly it doesn't work after a pod re-creation.
It turns out forcing 1.15.50 works just fine, there is probably a packaging error with 1.15.51

### What is the expected *correct* behavior?

nginx should be listening

### Relevant logs and/or screenshots

No log output from the container (blank)

### Environment

- Image version / tag:  1.15.51
- Host OS: Ubuntu / microk8s
    
### Possible fixes

Revert to 1.15.50

**Comment by ThaStealth** [comment]
Same issue

**Comment by tiredofit** [comment]
I'll need logs or something more than it doesn't work..

**Comment by ybizeul** [comment]
There's not much to it really, nginx isn't even running I think that's the problem, but it's not spitting out any error.

You couldn't reproduce it ?

**Comment by ollesson-allard** [comment]
Hi,

I have the same issues. I think i found the problem in the nginx.conf file


user <USER> <GROUP>;
worker_processes <WORKER_PROCESSES>;
worker_rlimit_nofile <WORKER_RLIMIT_NOFILE>;
pid /var/run/nginx.pid;

events {
    use epoll;
    worker_connections <WORKER_CONNECTIONS>;
    multi_accept on;
}

http {
    include /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    client_body_timeout <CLIENT_BODY_TIMEOUT>;
    send_timeout <SEND_TIMEOUT>;
    reset_timedout_connection on;

    keepalive_timeout  <KEEPALIVE_TIMEOUT>;
    keepalive_requests <KEEPALIVE_REQUESTS>;

    client_max_body_size <UPLOAD_MAX_SIZE>;
    client_body_buffer_size <CLIENT_BODY_BUFFER_SIZE>;

    fastcgi_buffers <FASTCGI_BUFFERS>;
    fastcgi_buffer_size <FASTCGI_BUFFER_SIZE>;

    server_tokens off;
    more_clear_headers Server;

    include /etc/nginx/nginx.conf.d/logging.conf;
    include /etc/nginx/nginx.conf.d/reverse_proxy.conf;
    include /etc/nginx/nginx.conf.d/bot_blocker.conf;
    include /etc/nginx/nginx.conf.d/ddos_protection.conf;
    include /etc/nginx/nginx.conf.d/open_file_cache.conf;
    include /etc/nginx/nginx.conf.d/compression_gzip.conf;
    include /etc/nginx/nginx.conf.d/compression_brotli.conf;
    include /etc/nginx/nginx.conf.d/monitoring.conf;

    # Do not delete - Upstream Configuration

    include /etc/nginx/conf.d/*.conf;
}

I hope this will help you. let me know if you need more information .

**Comment by tiredofit** [comment]
I got a report as well here: https://github.com/tiredofit/docker-nextcloud/issues/19 on another image.
I can't reproduce as I am running the images in a couple production environments (Fairly standard, docker-compose, Arch, 5.17 kernel, x86_64). 

What I'm going to do is rebuild all the images (tiredofit/alpine, tiredofit/nginx, tiredofit/nginx-php-fpm, and then each of these tagged releases) the process takes a few hours but I will be in touch when they are updated and we'll see what we come up with.

**Comment by tiredofit** [comment]
I've just rebuilt the images (:latest: and the tag) . Any better results?

**Comment by ollesson-allard** [comment]
i have update now  to the latest and it not working for me.

**Comment by ThaStealth** [comment]
Version 1.15.52 is starting in my environment

**Comment by ybizeul** [comment]
Same here, I think it's safe to close this now.
