### ISSUE TITLE
No ARM build of MariaDB

### ISSUE THREAD

**Issue by mitchplze** [tiredofit/docker-freescout#88]
Hello. I was pleased to see that docker-freescout was tagged for ARM devices, such as the Raspberry Pi. 

Unfortunately, the MariaDB container in the compose, is not built for ARM at all, and thus the stack is broken. 

Maybe I'm missing something, but it appears there is no working ARM functionality in this project.

**Comment by tiredofit** [comment]
Ahh, right, You can use any mariadb container, not just the `tiredofit/mariadb` one. I don't believe I build Arm/Arm64 versions regularly due to Github Actions being slow on my "free" account.

**Comment by tiredofit** [comment]
There is an arm version available now `tiredofit/mariadb:10.11`
