### ISSUE TITLE
Request for Postgresql support.

### ISSUE THREAD

**Issue by Aegis8** [tiredofit/docker-freescout#95]
Hello,

We would like to use docker-freescout, but we are restricted to using postgresql for our database backend. So we would really appreciate an update to this image.

I have read [ Issue #33 ](https://github.com/tiredofit/docker-freescout/issues/33).

Here is the psql one-liner, that was requested: 

`psql --dbname=postgresql://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME -c "SELECT * FROM users;" > /dev/null 2>&1`

If you need assistance in testing this, let me know.

**Comment by tiredofit** [comment]
This has been added as of `1.16.0` - An issue was found and we are now at `1.16.2`

**Comment by Aegis8** [comment]
@tiredofit Thank you very much, for the update!
